/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { User, UserList } from '../models/index';
import { UserFromJSON, UserToJSON, UserListFromJSON, UserListToJSON } from '../models/index';

export interface AdminAddUserRequest {
  user?: User;
}

export interface AdminDeleteUserRequest {
  id: string;
}

export interface AdminGetUserRequest {
  id: string;
}

export interface AdminGetUserListRequest {
  filter?: Array<string>;
  page?: number;
  pageSize?: number;
}

export interface AdminUpdateUserRequest {
  id: string;
  user?: User;
}

/**
 * AdminUserManagementApi - interface
 *
 * @export
 * @interface AdminUserManagementApiInterface
 */
export interface AdminUserManagementApiInterface {
  /**
   *
   * @summary Administration endpoint to manually add a user. Only accessible to superadmins.
   * @param {User} [user] A user object
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminUserManagementApiInterface
   */
  adminAddUserRaw(
    requestParameters: AdminAddUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>>;

  /**
   * Administration endpoint to manually add a user. Only accessible to superadmins.
   */
  adminAddUser(
    requestParameters: AdminAddUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User>;

  /**
   *
   * @summary Administration endpoint to delete a user. Only accessible to superadmins.
   * @param {string} id The ID of the user to delete
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminUserManagementApiInterface
   */
  adminDeleteUserRaw(
    requestParameters: AdminDeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>>;

  /**
   * Administration endpoint to delete a user. Only accessible to superadmins.
   */
  adminDeleteUser(
    requestParameters: AdminDeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void>;

  /**
   *
   * @summary Administration endpoint to return a user. Only accessible to superadmins.
   * @param {string} id The id of a user
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminUserManagementApiInterface
   */
  adminGetUserRaw(
    requestParameters: AdminGetUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>>;

  /**
   * Administration endpoint to return a user. Only accessible to superadmins.
   */
  adminGetUser(
    requestParameters: AdminGetUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User>;

  /**
   *
   * @summary Administration endpoint to return a list of users. Only accessible to superadmins.
   * @param {Array<string>} [filter] Fields to filter by
   * @param {number} [page] Set the page of items to return, defaults to 1
   * @param {number} [pageSize] Set the number of items per page, defaults to 25
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminUserManagementApiInterface
   */
  adminGetUserListRaw(
    requestParameters: AdminGetUserListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<UserList>>;

  /**
   * Administration endpoint to return a list of users. Only accessible to superadmins.
   */
  adminGetUserList(
    requestParameters: AdminGetUserListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<UserList>;

  /**
   *
   * @summary Administration endpoint to update a user. Only accessible to superadmins.
   * @param {string} id The ID of the user to update
   * @param {User} [user] A user object
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminUserManagementApiInterface
   */
  adminUpdateUserRaw(
    requestParameters: AdminUpdateUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>>;

  /**
   * Administration endpoint to update a user. Only accessible to superadmins.
   */
  adminUpdateUser(
    requestParameters: AdminUpdateUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User>;
}

/**
 *
 */
export class AdminUserManagementApi
  extends runtime.BaseAPI
  implements AdminUserManagementApiInterface
{
  /**
   * Administration endpoint to manually add a user. Only accessible to superadmins.
   */
  async adminAddUserRaw(
    requestParameters: AdminAddUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/admin/user`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: UserToJSON(requestParameters['user']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
  }

  /**
   * Administration endpoint to manually add a user. Only accessible to superadmins.
   */
  async adminAddUser(
    requestParameters: AdminAddUserRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User> {
    const response = await this.adminAddUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Administration endpoint to delete a user. Only accessible to superadmins.
   */
  async adminDeleteUserRaw(
    requestParameters: AdminDeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling adminDeleteUser().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/admin/user/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Administration endpoint to delete a user. Only accessible to superadmins.
   */
  async adminDeleteUser(
    requestParameters: AdminDeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.adminDeleteUserRaw(requestParameters, initOverrides);
  }

  /**
   * Administration endpoint to return a user. Only accessible to superadmins.
   */
  async adminGetUserRaw(
    requestParameters: AdminGetUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling adminGetUser().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/admin/user/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
  }

  /**
   * Administration endpoint to return a user. Only accessible to superadmins.
   */
  async adminGetUser(
    requestParameters: AdminGetUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User> {
    const response = await this.adminGetUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Administration endpoint to return a list of users. Only accessible to superadmins.
   */
  async adminGetUserListRaw(
    requestParameters: AdminGetUserListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<UserList>> {
    const queryParameters: any = {};

    if (requestParameters['filter'] != null) {
      queryParameters['filter'] = requestParameters['filter'];
    }

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['pageSize'] = requestParameters['pageSize'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/admin/user`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UserListFromJSON(jsonValue));
  }

  /**
   * Administration endpoint to return a list of users. Only accessible to superadmins.
   */
  async adminGetUserList(
    requestParameters: AdminGetUserListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<UserList> {
    const response = await this.adminGetUserListRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Administration endpoint to update a user. Only accessible to superadmins.
   */
  async adminUpdateUserRaw(
    requestParameters: AdminUpdateUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling adminUpdateUser().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/admin/user/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UserToJSON(requestParameters['user']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
  }

  /**
   * Administration endpoint to update a user. Only accessible to superadmins.
   */
  async adminUpdateUser(
    requestParameters: AdminUpdateUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User> {
    const response = await this.adminUpdateUserRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
