/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { Project, ProjectList } from '../models/index';
import {
  ProjectFromJSON,
  ProjectToJSON,
  ProjectListFromJSON,
  ProjectListToJSON,
} from '../models/index';

export interface AdminAddProjectRequest {
  project?: Project;
}

export interface AdminDeleteProjectRequest {
  id: string;
}

export interface AdminGetProjectRequest {
  id: string;
}

export interface AdminGetProjectListRequest {
  filter?: Array<string>;
  page?: number;
  pageSize?: number;
}

export interface AdminUpdateProjectRequest {
  id: string;
  project?: Project;
}

/**
 * AdminProjectManagementApi - interface
 *
 * @export
 * @interface AdminProjectManagementApiInterface
 */
export interface AdminProjectManagementApiInterface {
  /**
   *
   * @summary Administration endpoint to manually add a project. Only accessible to superadmins.
   * @param {Project} [project] A project object
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminProjectManagementApiInterface
   */
  adminAddProjectRaw(
    requestParameters: AdminAddProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Project>>;

  /**
   * Administration endpoint to manually add a project. Only accessible to superadmins.
   */
  adminAddProject(
    requestParameters: AdminAddProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Project>;

  /**
   *
   * @summary Administration endpoint to delete a project. Only accessible to superadmins.
   * @param {string} id The ID of the project to delete
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminProjectManagementApiInterface
   */
  adminDeleteProjectRaw(
    requestParameters: AdminDeleteProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>>;

  /**
   * Administration endpoint to delete a project. Only accessible to superadmins.
   */
  adminDeleteProject(
    requestParameters: AdminDeleteProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void>;

  /**
   *
   * @summary Administration endpoint to return a project. Only accessible to superadmins.
   * @param {string} id The id of a project
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminProjectManagementApiInterface
   */
  adminGetProjectRaw(
    requestParameters: AdminGetProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Project>>;

  /**
   * Administration endpoint to return a project. Only accessible to superadmins.
   */
  adminGetProject(
    requestParameters: AdminGetProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Project>;

  /**
   *
   * @summary Administration endpoint to return a list of projects. Only accessible to superadmins.
   * @param {Array<string>} [filter] Fields to filter by
   * @param {number} [page] Set the page of items to return, defaults to 1
   * @param {number} [pageSize] Set the number of items per page, defaults to 25
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminProjectManagementApiInterface
   */
  adminGetProjectListRaw(
    requestParameters: AdminGetProjectListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ProjectList>>;

  /**
   * Administration endpoint to return a list of projects. Only accessible to superadmins.
   */
  adminGetProjectList(
    requestParameters: AdminGetProjectListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ProjectList>;

  /**
   *
   * @summary Administration endpoint to update a project. Only accessible to superadmins.
   * @param {string} id The ID of the project to update
   * @param {Project} [project] A project object
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminProjectManagementApiInterface
   */
  adminUpdateProjectRaw(
    requestParameters: AdminUpdateProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Project>>;

  /**
   * Administration endpoint to update a project. Only accessible to superadmins.
   */
  adminUpdateProject(
    requestParameters: AdminUpdateProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Project>;
}

/**
 *
 */
export class AdminProjectManagementApi
  extends runtime.BaseAPI
  implements AdminProjectManagementApiInterface
{
  /**
   * Administration endpoint to manually add a project. Only accessible to superadmins.
   */
  async adminAddProjectRaw(
    requestParameters: AdminAddProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Project>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/admin/project`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ProjectToJSON(requestParameters['project']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
  }

  /**
   * Administration endpoint to manually add a project. Only accessible to superadmins.
   */
  async adminAddProject(
    requestParameters: AdminAddProjectRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Project> {
    const response = await this.adminAddProjectRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Administration endpoint to delete a project. Only accessible to superadmins.
   */
  async adminDeleteProjectRaw(
    requestParameters: AdminDeleteProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling adminDeleteProject().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/admin/project/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Administration endpoint to delete a project. Only accessible to superadmins.
   */
  async adminDeleteProject(
    requestParameters: AdminDeleteProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.adminDeleteProjectRaw(requestParameters, initOverrides);
  }

  /**
   * Administration endpoint to return a project. Only accessible to superadmins.
   */
  async adminGetProjectRaw(
    requestParameters: AdminGetProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Project>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling adminGetProject().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/admin/project/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
  }

  /**
   * Administration endpoint to return a project. Only accessible to superadmins.
   */
  async adminGetProject(
    requestParameters: AdminGetProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Project> {
    const response = await this.adminGetProjectRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Administration endpoint to return a list of projects. Only accessible to superadmins.
   */
  async adminGetProjectListRaw(
    requestParameters: AdminGetProjectListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ProjectList>> {
    const queryParameters: any = {};

    if (requestParameters['filter'] != null) {
      queryParameters['filter'] = requestParameters['filter'];
    }

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['pageSize'] = requestParameters['pageSize'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/admin/project`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ProjectListFromJSON(jsonValue));
  }

  /**
   * Administration endpoint to return a list of projects. Only accessible to superadmins.
   */
  async adminGetProjectList(
    requestParameters: AdminGetProjectListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ProjectList> {
    const response = await this.adminGetProjectListRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Administration endpoint to update a project. Only accessible to superadmins.
   */
  async adminUpdateProjectRaw(
    requestParameters: AdminUpdateProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Project>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling adminUpdateProject().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/admin/project/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: ProjectToJSON(requestParameters['project']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ProjectFromJSON(jsonValue));
  }

  /**
   * Administration endpoint to update a project. Only accessible to superadmins.
   */
  async adminUpdateProject(
    requestParameters: AdminUpdateProjectRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Project> {
    const response = await this.adminUpdateProjectRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
