/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { Artifact, ArtifactList } from '../models/index';
import {
  ArtifactFromJSON,
  ArtifactToJSON,
  ArtifactListFromJSON,
  ArtifactListToJSON,
} from '../models/index';

export interface DeleteArtifactRequest {
  id: string;
}

export interface DownloadArtifactRequest {
  id: string;
}

export interface GetArtifactRequest {
  id: string;
}

export interface GetArtifactListRequest {
  resultId?: string;
  runId?: string;
  page?: number;
  pageSize?: number;
}

export interface UploadArtifactRequest {
  filename: string;
  file: Blob;
  resultId?: string;
  runId?: string;
  additionalMetadata?: object;
}

export interface ViewArtifactRequest {
  id: string;
}

/**
 * ArtifactApi - interface
 *
 * @export
 * @interface ArtifactApiInterface
 */
export interface ArtifactApiInterface {
  /**
   *
   * @summary Delete an artifact
   * @param {string} id ID of artifact to delete
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ArtifactApiInterface
   */
  deleteArtifactRaw(
    requestParameters: DeleteArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>>;

  /**
   * Delete an artifact
   */
  deleteArtifact(
    requestParameters: DeleteArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void>;

  /**
   *
   * @summary Download an artifact
   * @param {string} id ID of artifact to return
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ArtifactApiInterface
   */
  downloadArtifactRaw(
    requestParameters: DownloadArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Blob>>;

  /**
   * Download an artifact
   */
  downloadArtifact(
    requestParameters: DownloadArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Blob>;

  /**
   *
   * @summary Get a single artifact
   * @param {string} id ID of artifact to return
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ArtifactApiInterface
   */
  getArtifactRaw(
    requestParameters: GetArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Artifact>>;

  /**
   * Get a single artifact
   */
  getArtifact(
    requestParameters: GetArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Artifact>;

  /**
   *
   * @summary Get a (filtered) list of artifacts
   * @param {string} [resultId] The result ID to filter by
   * @param {string} [runId] The run ID to filter by
   * @param {number} [page] Set the page of items to return, defaults to 1
   * @param {number} [pageSize] Set the number of items per page, defaults to 25
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ArtifactApiInterface
   */
  getArtifactListRaw(
    requestParameters: GetArtifactListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ArtifactList>>;

  /**
   * Get a (filtered) list of artifacts
   */
  getArtifactList(
    requestParameters: GetArtifactListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ArtifactList>;

  /**
   *
   * @summary Uploads a test run artifact
   * @param {string} filename name of the file
   * @param {Blob} file file to upload
   * @param {string} [resultId] ID of result to attach artifact to (mutually exclusive with runId)
   * @param {string} [runId] ID of run to attach artifact to (mutually exclusive with resultId)
   * @param {object} [additionalMetadata] Additional data to pass to server
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ArtifactApiInterface
   */
  uploadArtifactRaw(
    requestParameters: UploadArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Artifact>>;

  /**
   * Uploads a test run artifact
   */
  uploadArtifact(
    requestParameters: UploadArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Artifact>;

  /**
   *
   * @summary Stream an artifact directly to the client/browser
   * @param {string} id ID of artifact to return
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ArtifactApiInterface
   */
  viewArtifactRaw(
    requestParameters: ViewArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Blob>>;

  /**
   * Stream an artifact directly to the client/browser
   */
  viewArtifact(
    requestParameters: ViewArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Blob>;
}

/**
 *
 */
export class ArtifactApi extends runtime.BaseAPI implements ArtifactApiInterface {
  /**
   * Delete an artifact
   */
  async deleteArtifactRaw(
    requestParameters: DeleteArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteArtifact().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/artifact/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete an artifact
   */
  async deleteArtifact(
    requestParameters: DeleteArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.deleteArtifactRaw(requestParameters, initOverrides);
  }

  /**
   * Download an artifact
   */
  async downloadArtifactRaw(
    requestParameters: DownloadArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Blob>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling downloadArtifact().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/artifact/{id}/download`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.BlobApiResponse(response);
  }

  /**
   * Download an artifact
   */
  async downloadArtifact(
    requestParameters: DownloadArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Blob> {
    const response = await this.downloadArtifactRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get a single artifact
   */
  async getArtifactRaw(
    requestParameters: GetArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Artifact>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getArtifact().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/artifact/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ArtifactFromJSON(jsonValue));
  }

  /**
   * Get a single artifact
   */
  async getArtifact(
    requestParameters: GetArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Artifact> {
    const response = await this.getArtifactRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get a (filtered) list of artifacts
   */
  async getArtifactListRaw(
    requestParameters: GetArtifactListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ArtifactList>> {
    const queryParameters: any = {};

    if (requestParameters['resultId'] != null) {
      queryParameters['resultId'] = requestParameters['resultId'];
    }

    if (requestParameters['runId'] != null) {
      queryParameters['runId'] = requestParameters['runId'];
    }

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['pageSize'] = requestParameters['pageSize'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/artifact`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ArtifactListFromJSON(jsonValue));
  }

  /**
   * Get a (filtered) list of artifacts
   */
  async getArtifactList(
    requestParameters: GetArtifactListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ArtifactList> {
    const response = await this.getArtifactListRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Uploads a test run artifact
   */
  async uploadArtifactRaw(
    requestParameters: UploadArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Artifact>> {
    if (requestParameters['filename'] == null) {
      throw new runtime.RequiredError(
        'filename',
        'Required parameter "filename" was null or undefined when calling uploadArtifact().'
      );
    }

    if (requestParameters['file'] == null) {
      throw new runtime.RequiredError(
        'file',
        'Required parameter "file" was null or undefined when calling uploadArtifact().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const consumes: runtime.Consume[] = [{ contentType: 'multipart/form-data' }];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters['resultId'] != null) {
      formParams.append('resultId', requestParameters['resultId'] as any);
    }

    if (requestParameters['runId'] != null) {
      formParams.append('runId', requestParameters['runId'] as any);
    }

    if (requestParameters['filename'] != null) {
      formParams.append('filename', requestParameters['filename'] as any);
    }

    if (requestParameters['file'] != null) {
      formParams.append('file', requestParameters['file'] as any);
    }

    if (requestParameters['additionalMetadata'] != null) {
      formParams.append(
        'additionalMetadata',
        new Blob([JSON.stringify(objectToJSON(requestParameters['additionalMetadata']))], {
          type: 'application/json',
        })
      );
    }

    let urlPath = `/artifact`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ArtifactFromJSON(jsonValue));
  }

  /**
   * Uploads a test run artifact
   */
  async uploadArtifact(
    requestParameters: UploadArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Artifact> {
    const response = await this.uploadArtifactRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Stream an artifact directly to the client/browser
   */
  async viewArtifactRaw(
    requestParameters: ViewArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Blob>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling viewArtifact().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/artifact/{id}/view`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.BlobApiResponse(response);
  }

  /**
   * Stream an artifact directly to the client/browser
   */
  async viewArtifact(
    requestParameters: ViewArtifactRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Blob> {
    const response = await this.viewArtifactRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
