/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { Dashboard, DashboardList } from '../models/index';
import {
  DashboardFromJSON,
  DashboardToJSON,
  DashboardListFromJSON,
  DashboardListToJSON,
} from '../models/index';

export interface AddDashboardRequest {
  dashboard?: Dashboard;
}

export interface DeleteDashboardRequest {
  id: string;
}

export interface GetDashboardRequest {
  id: string;
}

export interface GetDashboardListRequest {
  filter?: Array<string>;
  projectId?: string;
  userId?: string;
  page?: number;
  pageSize?: number;
}

export interface UpdateDashboardRequest {
  id: string;
  dashboard?: Dashboard;
}

/**
 * DashboardApi - interface
 *
 * @export
 * @interface DashboardApiInterface
 */
export interface DashboardApiInterface {
  /**
   *
   * @summary Create a dashboard
   * @param {Dashboard} [dashboard] A dashboard object
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DashboardApiInterface
   */
  addDashboardRaw(
    requestParameters: AddDashboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Dashboard>>;

  /**
   * Create a dashboard
   */
  addDashboard(
    requestParameters: AddDashboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Dashboard>;

  /**
   *
   * @summary Delete a dashboard
   * @param {string} id ID of dashboard to delete
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DashboardApiInterface
   */
  deleteDashboardRaw(
    requestParameters: DeleteDashboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>>;

  /**
   * Delete a dashboard
   */
  deleteDashboard(
    requestParameters: DeleteDashboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void>;

  /**
   *
   * @summary Get a single dashboard by ID
   * @param {string} id ID of test dashboard
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DashboardApiInterface
   */
  getDashboardRaw(
    requestParameters: GetDashboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Dashboard>>;

  /**
   * Get a single dashboard by ID
   */
  getDashboard(
    requestParameters: GetDashboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Dashboard>;

  /**
   *
   * @summary Get a list of dashboards
   * @param {Array<string>} [filter] Fields to filter by
   * @param {string} [projectId] Filter dashboards by project ID
   * @param {string} [userId] Filter dashboards by user ID
   * @param {number} [page] Set the page of items to return, defaults to 1
   * @param {number} [pageSize] Set the number of items per page, defaults to 25
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DashboardApiInterface
   */
  getDashboardListRaw(
    requestParameters: GetDashboardListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<DashboardList>>;

  /**
   * Get a list of dashboards
   */
  getDashboardList(
    requestParameters: GetDashboardListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<DashboardList>;

  /**
   *
   * @summary Update a dashboard
   * @param {string} id ID of test dashboard
   * @param {Dashboard} [dashboard] A dashboard object
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DashboardApiInterface
   */
  updateDashboardRaw(
    requestParameters: UpdateDashboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Dashboard>>;

  /**
   * Update a dashboard
   */
  updateDashboard(
    requestParameters: UpdateDashboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Dashboard>;
}

/**
 *
 */
export class DashboardApi extends runtime.BaseAPI implements DashboardApiInterface {
  /**
   * Create a dashboard
   */
  async addDashboardRaw(
    requestParameters: AddDashboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Dashboard>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/dashboard`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: DashboardToJSON(requestParameters['dashboard']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => DashboardFromJSON(jsonValue));
  }

  /**
   * Create a dashboard
   */
  async addDashboard(
    requestParameters: AddDashboardRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Dashboard> {
    const response = await this.addDashboardRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Delete a dashboard
   */
  async deleteDashboardRaw(
    requestParameters: DeleteDashboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteDashboard().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/dashboard/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete a dashboard
   */
  async deleteDashboard(
    requestParameters: DeleteDashboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.deleteDashboardRaw(requestParameters, initOverrides);
  }

  /**
   * Get a single dashboard by ID
   */
  async getDashboardRaw(
    requestParameters: GetDashboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Dashboard>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getDashboard().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/dashboard/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => DashboardFromJSON(jsonValue));
  }

  /**
   * Get a single dashboard by ID
   */
  async getDashboard(
    requestParameters: GetDashboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Dashboard> {
    const response = await this.getDashboardRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get a list of dashboards
   */
  async getDashboardListRaw(
    requestParameters: GetDashboardListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<DashboardList>> {
    const queryParameters: any = {};

    if (requestParameters['filter'] != null) {
      queryParameters['filter'] = requestParameters['filter'];
    }

    if (requestParameters['projectId'] != null) {
      queryParameters['project_id'] = requestParameters['projectId'];
    }

    if (requestParameters['userId'] != null) {
      queryParameters['user_id'] = requestParameters['userId'];
    }

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['pageSize'] = requestParameters['pageSize'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/dashboard`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => DashboardListFromJSON(jsonValue));
  }

  /**
   * Get a list of dashboards
   */
  async getDashboardList(
    requestParameters: GetDashboardListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<DashboardList> {
    const response = await this.getDashboardListRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update a dashboard
   */
  async updateDashboardRaw(
    requestParameters: UpdateDashboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Dashboard>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling updateDashboard().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/dashboard/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: DashboardToJSON(requestParameters['dashboard']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => DashboardFromJSON(jsonValue));
  }

  /**
   * Update a dashboard
   */
  async updateDashboard(
    requestParameters: UpdateDashboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Dashboard> {
    const response = await this.updateDashboardRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
