/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { Group, GroupList } from '../models/index';
import { GroupFromJSON, GroupToJSON, GroupListFromJSON, GroupListToJSON } from '../models/index';

export interface AddGroupRequest {
  group?: Group;
}

export interface GetGroupRequest {
  id: string;
}

export interface GetGroupListRequest {
  page?: number;
  pageSize?: number;
}

export interface UpdateGroupRequest {
  id: string;
  group?: Group;
}

/**
 * GroupApi - interface
 *
 * @export
 * @interface GroupApiInterface
 */
export interface GroupApiInterface {
  /**
   *
   * @summary Create a new group
   * @param {Group} [group] A group object
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApiInterface
   */
  addGroupRaw(
    requestParameters: AddGroupRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Group>>;

  /**
   * Create a new group
   */
  addGroup(
    requestParameters: AddGroupRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Group>;

  /**
   *
   * @summary Get a group
   * @param {string} id The ID of the group
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApiInterface
   */
  getGroupRaw(
    requestParameters: GetGroupRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Group>>;

  /**
   * Get a group
   */
  getGroup(
    requestParameters: GetGroupRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Group>;

  /**
   *
   * @summary Get a list of groups
   * @param {number} [page] Set the page of items to return, defaults to 1
   * @param {number} [pageSize] Set the number of items per page, defaults to 25
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApiInterface
   */
  getGroupListRaw(
    requestParameters: GetGroupListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GroupList>>;

  /**
   * Get a list of groups
   */
  getGroupList(
    requestParameters: GetGroupListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GroupList>;

  /**
   *
   * @summary Update a group
   * @param {string} id The ID of the group
   * @param {Group} [group] A group object
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApiInterface
   */
  updateGroupRaw(
    requestParameters: UpdateGroupRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Group>>;

  /**
   * Update a group
   */
  updateGroup(
    requestParameters: UpdateGroupRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Group>;
}

/**
 *
 */
export class GroupApi extends runtime.BaseAPI implements GroupApiInterface {
  /**
   * Create a new group
   */
  async addGroupRaw(
    requestParameters: AddGroupRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Group>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/group`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: GroupToJSON(requestParameters['group']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => GroupFromJSON(jsonValue));
  }

  /**
   * Create a new group
   */
  async addGroup(
    requestParameters: AddGroupRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Group> {
    const response = await this.addGroupRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get a group
   */
  async getGroupRaw(
    requestParameters: GetGroupRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Group>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getGroup().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/group/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => GroupFromJSON(jsonValue));
  }

  /**
   * Get a group
   */
  async getGroup(
    requestParameters: GetGroupRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Group> {
    const response = await this.getGroupRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get a list of groups
   */
  async getGroupListRaw(
    requestParameters: GetGroupListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GroupList>> {
    const queryParameters: any = {};

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['pageSize'] = requestParameters['pageSize'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/group`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => GroupListFromJSON(jsonValue));
  }

  /**
   * Get a list of groups
   */
  async getGroupList(
    requestParameters: GetGroupListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GroupList> {
    const response = await this.getGroupListRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update a group
   */
  async updateGroupRaw(
    requestParameters: UpdateGroupRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Group>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling updateGroup().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/group/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: GroupToJSON(requestParameters['group']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => GroupFromJSON(jsonValue));
  }

  /**
   * Update a group
   */
  async updateGroup(
    requestParameters: UpdateGroupRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Group> {
    const response = await this.updateGroupRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
