/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { Health, HealthInfo } from '../models/index';
import {
  HealthFromJSON,
  HealthToJSON,
  HealthInfoFromJSON,
  HealthInfoToJSON,
} from '../models/index';

/**
 * HealthApi - interface
 *
 * @export
 * @interface HealthApiInterface
 */
export interface HealthApiInterface {
  /**
   *
   * @summary Get a health report for the database
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof HealthApiInterface
   */
  getDatabaseHealthRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Health>>;

  /**
   * Get a health report for the database
   */
  getDatabaseHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Health>;

  /**
   *
   * @summary Get a general health report
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof HealthApiInterface
   */
  getHealthRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Health>>;

  /**
   * Get a general health report
   */
  getHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Health>;

  /**
   *
   * @summary Get information about the server
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof HealthApiInterface
   */
  getHealthInfoRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<HealthInfo>>;

  /**
   * Get information about the server
   */
  getHealthInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthInfo>;
}

/**
 *
 */
export class HealthApi extends runtime.BaseAPI implements HealthApiInterface {
  /**
   * Get a health report for the database
   */
  async getDatabaseHealthRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Health>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/health/database`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => HealthFromJSON(jsonValue));
  }

  /**
   * Get a health report for the database
   */
  async getDatabaseHealth(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Health> {
    const response = await this.getDatabaseHealthRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get a general health report
   */
  async getHealthRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Health>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/health`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => HealthFromJSON(jsonValue));
  }

  /**
   * Get a general health report
   */
  async getHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Health> {
    const response = await this.getHealthRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get information about the server
   */
  async getHealthInfoRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<HealthInfo>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/health/info`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => HealthInfoFromJSON(jsonValue));
  }

  /**
   * Get information about the server
   */
  async getHealthInfo(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<HealthInfo> {
    const response = await this.getHealthInfoRaw(initOverrides);
    return await response.value();
  }
}
