/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Import,
} from '../models/index';
import {
    ImportFromJSON,
    ImportToJSON,
} from '../models/index';

export interface AddImportRequest {
    importFile: Blob;
    project?: string;
    metadata?: object;
    source?: string;
}

export interface GetImportRequest {
    id: string;
}

/**
 * ImportApi - interface
 * 
 * @export
 * @interface ImportApiInterface
 */
export interface ImportApiInterface {
    /**
     * 
     * @summary Import a file into Ibutsu. This can be either a JUnit XML file, or an Ibutsu archive
     * @param {Blob} importFile The file to import
     * @param {string} [project] The project associated with this import
     * @param {object} [metadata] Additional metadata about imported run
     * @param {string} [source] The source of this import
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImportApiInterface
     */
    addImportRaw(requestParameters: AddImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Import>>;

    /**
     * Import a file into Ibutsu. This can be either a JUnit XML file, or an Ibutsu archive
     */
    addImport(requestParameters: AddImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Import>;

    /**
     * 
     * @summary Get the status of an import
     * @param {string} id The ID of the import
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImportApiInterface
     */
    getImportRaw(requestParameters: GetImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Import>>;

    /**
     * Get the status of an import
     */
    getImport(requestParameters: GetImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Import>;

}

/**
 * 
 */
export class ImportApi extends runtime.BaseAPI implements ImportApiInterface {

    /**
     * Import a file into Ibutsu. This can be either a JUnit XML file, or an Ibutsu archive
     */
    async addImportRaw(requestParameters: AddImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Import>> {
        if (requestParameters['importFile'] == null) {
            throw new runtime.RequiredError(
                'importFile',
                'Required parameter "importFile" was null or undefined when calling addImport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['importFile'] != null) {
            formParams.append('importFile', requestParameters['importFile'] as any);
        }

        if (requestParameters['project'] != null) {
            formParams.append('project', requestParameters['project'] as any);
        }

        if (requestParameters['metadata'] != null) {
            formParams.append('metadata', new Blob([JSON.stringify(objectToJSON(requestParameters['metadata']))], { type: "application/json", }));
                    }

        if (requestParameters['source'] != null) {
            formParams.append('source', requestParameters['source'] as any);
        }


        let urlPath = `/import`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportFromJSON(jsonValue));
    }

    /**
     * Import a file into Ibutsu. This can be either a JUnit XML file, or an Ibutsu archive
     */
    async addImport(requestParameters: AddImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Import> {
        const response = await this.addImportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the status of an import
     */
    async getImportRaw(requestParameters: GetImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Import>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getImport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/import/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportFromJSON(jsonValue));
    }

    /**
     * Get the status of an import
     */
    async getImport(requestParameters: GetImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Import> {
        const response = await this.getImportRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
