/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  AccountRecovery,
  AccountRegistration,
  AccountReset,
  Credentials,
  LoginConfig,
  LoginError,
  LoginSupport,
  LoginToken,
} from '../models/index';
import {
  AccountRecoveryFromJSON,
  AccountRecoveryToJSON,
  AccountRegistrationFromJSON,
  AccountRegistrationToJSON,
  AccountResetFromJSON,
  AccountResetToJSON,
  CredentialsFromJSON,
  CredentialsToJSON,
  LoginConfigFromJSON,
  LoginConfigToJSON,
  LoginErrorFromJSON,
  LoginErrorToJSON,
  LoginSupportFromJSON,
  LoginSupportToJSON,
  LoginTokenFromJSON,
  LoginTokenToJSON,
} from '../models/index';

export interface ActivateRequest {
  activationCode: string;
}

export interface AuthRequest {
  provider: string;
}

export interface ConfigRequest {
  provider: string;
}

export interface LoginRequest {
  credentials?: Credentials;
}

export interface RecoverRequest {
  accountRecovery?: AccountRecovery;
}

export interface RegisterRequest {
  accountRegistration?: AccountRegistration;
}

export interface ResetPasswordRequest {
  accountReset?: AccountReset;
}

/**
 * LoginApi - interface
 *
 * @export
 * @interface LoginApiInterface
 */
export interface LoginApiInterface {
  /**
   *
   * @param {string} activationCode The activation code
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LoginApiInterface
   */
  activateRaw(
    requestParameters: ActivateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  activate(
    requestParameters: ActivateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void>;

  /**
   *
   * @param {string} provider The login provider\&#39;s configuration
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LoginApiInterface
   */
  authRaw(
    requestParameters: AuthRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  auth(
    requestParameters: AuthRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void>;

  /**
   *
   * @param {string} provider The login provider\&#39;s configuration
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LoginApiInterface
   */
  configRaw(
    requestParameters: ConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LoginConfig>>;

  /**
   */
  config(
    requestParameters: ConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LoginConfig>;

  /**
   *
   * @param {Credentials} [credentials] A login object
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LoginApiInterface
   */
  loginRaw(
    requestParameters: LoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LoginToken>>;

  /**
   */
  login(
    requestParameters: LoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LoginToken>;

  /**
   *
   * @param {AccountRecovery} [accountRecovery] A user recovering their password
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LoginApiInterface
   */
  recoverRaw(
    requestParameters: RecoverRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  recover(
    requestParameters: RecoverRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void>;

  /**
   *
   * @param {AccountRegistration} [accountRegistration] A user registering their account
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LoginApiInterface
   */
  registerRaw(
    requestParameters: RegisterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  register(
    requestParameters: RegisterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void>;

  /**
   *
   * @param {AccountReset} [accountReset] A user resetting their password
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LoginApiInterface
   */
  resetPasswordRaw(
    requestParameters: ResetPasswordRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  resetPassword(
    requestParameters: ResetPasswordRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void>;

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof LoginApiInterface
   */
  supportRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LoginSupport>>;

  /**
   */
  support(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginSupport>;
}

/**
 *
 */
export class LoginApi extends runtime.BaseAPI implements LoginApiInterface {
  /**
   */
  async activateRaw(
    requestParameters: ActivateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['activationCode'] == null) {
      throw new runtime.RequiredError(
        'activationCode',
        'Required parameter "activationCode" was null or undefined when calling activate().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/login/activate/{activation_code}`;
    urlPath = urlPath.replace(
      `{${'activation_code'}}`,
      encodeURIComponent(String(requestParameters['activationCode']))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async activate(
    requestParameters: ActivateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.activateRaw(requestParameters, initOverrides);
  }

  /**
   */
  async authRaw(
    requestParameters: AuthRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['provider'] == null) {
      throw new runtime.RequiredError(
        'provider',
        'Required parameter "provider" was null or undefined when calling auth().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/login/auth/{provider}`;
    urlPath = urlPath.replace(
      `{${'provider'}}`,
      encodeURIComponent(String(requestParameters['provider']))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async auth(
    requestParameters: AuthRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.authRaw(requestParameters, initOverrides);
  }

  /**
   */
  async configRaw(
    requestParameters: ConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LoginConfig>> {
    if (requestParameters['provider'] == null) {
      throw new runtime.RequiredError(
        'provider',
        'Required parameter "provider" was null or undefined when calling config().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/login/config/{provider}`;
    urlPath = urlPath.replace(
      `{${'provider'}}`,
      encodeURIComponent(String(requestParameters['provider']))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => LoginConfigFromJSON(jsonValue));
  }

  /**
   */
  async config(
    requestParameters: ConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LoginConfig> {
    const response = await this.configRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async loginRaw(
    requestParameters: LoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LoginToken>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/login`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CredentialsToJSON(requestParameters['credentials']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => LoginTokenFromJSON(jsonValue));
  }

  /**
   */
  async login(
    requestParameters: LoginRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LoginToken> {
    const response = await this.loginRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async recoverRaw(
    requestParameters: RecoverRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/login/recover`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: AccountRecoveryToJSON(requestParameters['accountRecovery']),
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async recover(
    requestParameters: RecoverRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.recoverRaw(requestParameters, initOverrides);
  }

  /**
   */
  async registerRaw(
    requestParameters: RegisterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/login/register`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: AccountRegistrationToJSON(requestParameters['accountRegistration']),
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async register(
    requestParameters: RegisterRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.registerRaw(requestParameters, initOverrides);
  }

  /**
   */
  async resetPasswordRaw(
    requestParameters: ResetPasswordRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/login/reset-password`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: AccountResetToJSON(requestParameters['accountReset']),
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async resetPassword(
    requestParameters: ResetPasswordRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.resetPasswordRaw(requestParameters, initOverrides);
  }

  /**
   */
  async supportRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LoginSupport>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/login/support`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => LoginSupportFromJSON(jsonValue));
  }

  /**
   */
  async support(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginSupport> {
    const response = await this.supportRaw(initOverrides);
    return await response.value();
  }
}
