/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Result,
  ResultList,
} from '../models/index';
import {
    ResultFromJSON,
    ResultToJSON,
    ResultListFromJSON,
    ResultListToJSON,
} from '../models/index';

export interface AddResultRequest {
    result?: Result;
}

export interface GetResultRequest {
    id: string;
}

export interface GetResultListRequest {
    filter?: Array<string>;
    estimate?: boolean;
    page?: number;
    pageSize?: number;
}

export interface UpdateResultRequest {
    id: string;
    result?: Result;
}

/**
 * ResultApi - interface
 * 
 * @export
 * @interface ResultApiInterface
 */
export interface ResultApiInterface {
    /**
     * 
     * @summary Create a test result
     * @param {Result} [result] Result item
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResultApiInterface
     */
    addResultRaw(requestParameters: AddResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Result>>;

    /**
     * Create a test result
     */
    addResult(requestParameters: AddResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Result>;

    /**
     * 
     * @summary Get a single result
     * @param {string} id ID of result to return (uuid required)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResultApiInterface
     */
    getResultRaw(requestParameters: GetResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Result>>;

    /**
     * Get a single result
     */
    getResult(requestParameters: GetResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Result>;

    /**
     * The `filter` parameter takes a list of filters to apply in the form of:      {name}{operator}{value}  where:    - `name` is any valid column in the database   - `operator` is one of `=`, `!`, `＞`, `＜`, `)`, `(`, `~`, `*`   - `value` is what you want to filter by  Operators are simple correspondents to MongoDB\'s query selectors:    - `=` becomes `$eq`   - `!` becomes `$ne`   - `＞` becomes `$gt`   - `＜` becomes `$lt`   - `)` becomes `$gte`   - `(` becomes `$lte`   - `~` becomes `$regex`   - `*` becomes `$in`   - `@` becomes `$exists`  Notes:  - For the `$exists` operator, \"true\", \"t\", \"yes\", \"y\" and `1` will all be considered true,   all other values are considered false.  Example queries:      /result?filter=metadata.run=63fe5     /result?filter=test_id~neg     /result?filter=result!passed 
     * @summary Get the list of results.
     * @param {Array<string>} [filter] Fields to filter by
     * @param {boolean} [estimate] Return an estimated count
     * @param {number} [page] Set the page of items to return, defaults to 1
     * @param {number} [pageSize] Set the number of items per page, defaults to 25
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResultApiInterface
     */
    getResultListRaw(requestParameters: GetResultListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultList>>;

    /**
     * The `filter` parameter takes a list of filters to apply in the form of:      {name}{operator}{value}  where:    - `name` is any valid column in the database   - `operator` is one of `=`, `!`, `＞`, `＜`, `)`, `(`, `~`, `*`   - `value` is what you want to filter by  Operators are simple correspondents to MongoDB\'s query selectors:    - `=` becomes `$eq`   - `!` becomes `$ne`   - `＞` becomes `$gt`   - `＜` becomes `$lt`   - `)` becomes `$gte`   - `(` becomes `$lte`   - `~` becomes `$regex`   - `*` becomes `$in`   - `@` becomes `$exists`  Notes:  - For the `$exists` operator, \"true\", \"t\", \"yes\", \"y\" and `1` will all be considered true,   all other values are considered false.  Example queries:      /result?filter=metadata.run=63fe5     /result?filter=test_id~neg     /result?filter=result!passed 
     * Get the list of results.
     */
    getResultList(requestParameters: GetResultListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultList>;

    /**
     * 
     * @summary Updates a single result
     * @param {string} id ID of result to update
     * @param {Result} [result] Result item
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ResultApiInterface
     */
    updateResultRaw(requestParameters: UpdateResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Result>>;

    /**
     * Updates a single result
     */
    updateResult(requestParameters: UpdateResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Result>;

}

/**
 * 
 */
export class ResultApi extends runtime.BaseAPI implements ResultApiInterface {

    /**
     * Create a test result
     */
    async addResultRaw(requestParameters: AddResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Result>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/result`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResultToJSON(requestParameters['result']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultFromJSON(jsonValue));
    }

    /**
     * Create a test result
     */
    async addResult(requestParameters: AddResultRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Result> {
        const response = await this.addResultRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a single result
     */
    async getResultRaw(requestParameters: GetResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Result>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getResult().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/result/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultFromJSON(jsonValue));
    }

    /**
     * Get a single result
     */
    async getResult(requestParameters: GetResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Result> {
        const response = await this.getResultRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The `filter` parameter takes a list of filters to apply in the form of:      {name}{operator}{value}  where:    - `name` is any valid column in the database   - `operator` is one of `=`, `!`, `＞`, `＜`, `)`, `(`, `~`, `*`   - `value` is what you want to filter by  Operators are simple correspondents to MongoDB\'s query selectors:    - `=` becomes `$eq`   - `!` becomes `$ne`   - `＞` becomes `$gt`   - `＜` becomes `$lt`   - `)` becomes `$gte`   - `(` becomes `$lte`   - `~` becomes `$regex`   - `*` becomes `$in`   - `@` becomes `$exists`  Notes:  - For the `$exists` operator, \"true\", \"t\", \"yes\", \"y\" and `1` will all be considered true,   all other values are considered false.  Example queries:      /result?filter=metadata.run=63fe5     /result?filter=test_id~neg     /result?filter=result!passed 
     * Get the list of results.
     */
    async getResultListRaw(requestParameters: GetResultListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultList>> {
        const queryParameters: any = {};

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['estimate'] != null) {
            queryParameters['estimate'] = requestParameters['estimate'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/result`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultListFromJSON(jsonValue));
    }

    /**
     * The `filter` parameter takes a list of filters to apply in the form of:      {name}{operator}{value}  where:    - `name` is any valid column in the database   - `operator` is one of `=`, `!`, `＞`, `＜`, `)`, `(`, `~`, `*`   - `value` is what you want to filter by  Operators are simple correspondents to MongoDB\'s query selectors:    - `=` becomes `$eq`   - `!` becomes `$ne`   - `＞` becomes `$gt`   - `＜` becomes `$lt`   - `)` becomes `$gte`   - `(` becomes `$lte`   - `~` becomes `$regex`   - `*` becomes `$in`   - `@` becomes `$exists`  Notes:  - For the `$exists` operator, \"true\", \"t\", \"yes\", \"y\" and `1` will all be considered true,   all other values are considered false.  Example queries:      /result?filter=metadata.run=63fe5     /result?filter=test_id~neg     /result?filter=result!passed 
     * Get the list of results.
     */
    async getResultList(requestParameters: GetResultListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultList> {
        const response = await this.getResultListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a single result
     */
    async updateResultRaw(requestParameters: UpdateResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Result>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateResult().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/result/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ResultToJSON(requestParameters['result']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultFromJSON(jsonValue));
    }

    /**
     * Updates a single result
     */
    async updateResult(requestParameters: UpdateResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Result> {
        const response = await this.updateResultRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
