/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Run,
  RunList,
  UpdateRun,
} from '../models/index';
import {
    RunFromJSON,
    RunToJSON,
    RunListFromJSON,
    RunListToJSON,
    UpdateRunFromJSON,
    UpdateRunToJSON,
} from '../models/index';

export interface AddRunRequest {
    run?: Run;
}

export interface BulkUpdateRequest {
    filter?: Array<string>;
    pageSize?: number;
    updateRun?: UpdateRun;
}

export interface GetRunRequest {
    id: string;
}

export interface GetRunListRequest {
    filter?: Array<string>;
    estimate?: boolean;
    page?: number;
    pageSize?: number;
}

export interface UpdateRunRequest {
    id: string;
    run?: Run;
}

/**
 * RunApi - interface
 * 
 * @export
 * @interface RunApiInterface
 */
export interface RunApiInterface {
    /**
     * 
     * @summary Create a run
     * @param {Run} [run] A run object
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunApiInterface
     */
    addRunRaw(requestParameters: AddRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Run>>;

    /**
     * Create a run
     */
    addRun(requestParameters: AddRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Run>;

    /**
     * 
     * @summary Update multiple runs with common metadata
     * @param {Array<string>} [filter] Fields to filter by
     * @param {number} [pageSize] Set the number of items per page, defaults to 25
     * @param {UpdateRun} [updateRun] Run metadata updates
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunApiInterface
     */
    bulkUpdateRaw(requestParameters: BulkUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RunList>>;

    /**
     * Update multiple runs with common metadata
     */
    bulkUpdate(requestParameters: BulkUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RunList>;

    /**
     * 
     * @summary Get a single run by ID (uuid required)
     * @param {string} id ID of test run
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunApiInterface
     */
    getRunRaw(requestParameters: GetRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Run>>;

    /**
     * Get a single run by ID (uuid required)
     */
    getRun(requestParameters: GetRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Run>;

    /**
     * The `filter` parameter takes a list of filters to apply in the form of:       {name}{operator}{value}   where:    - `name` is any valid column in the database   - `operator` is one of `=`, `!`, `＞`, `＜`, `)`, `(`, `~`, `*`   - `value` is what you want to filter by  Operators are simple correspondents to MongoDB\'s query selectors:    - `=` becomes `$eq`   - `!` becomes `$ne`   - `＞` becomes `$gt`   - `＜` becomes `$lt`   - `)` becomes `$gte`   - `(` becomes `$lte`   - `~` becomes `$regex`   - `*` becomes `$in`   - `@` becomes `$exists`  Notes:  - For the `$exists` operator, \"true\", \"t\", \"yes\", \"y\" and `1` will all be considered true,   all other values are considered false.  Example queries:      /run?filter=metadata.jenkins.job_name=jenkins_job     /run?filter=summary.failures>0 
     * @summary Get a list of the test runs
     * @param {Array<string>} [filter] Fields to filter by
     * @param {boolean} [estimate] Return an estimated count
     * @param {number} [page] Set the page of items to return, defaults to 1
     * @param {number} [pageSize] Set the number of items per page, defaults to 25
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunApiInterface
     */
    getRunListRaw(requestParameters: GetRunListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RunList>>;

    /**
     * The `filter` parameter takes a list of filters to apply in the form of:       {name}{operator}{value}   where:    - `name` is any valid column in the database   - `operator` is one of `=`, `!`, `＞`, `＜`, `)`, `(`, `~`, `*`   - `value` is what you want to filter by  Operators are simple correspondents to MongoDB\'s query selectors:    - `=` becomes `$eq`   - `!` becomes `$ne`   - `＞` becomes `$gt`   - `＜` becomes `$lt`   - `)` becomes `$gte`   - `(` becomes `$lte`   - `~` becomes `$regex`   - `*` becomes `$in`   - `@` becomes `$exists`  Notes:  - For the `$exists` operator, \"true\", \"t\", \"yes\", \"y\" and `1` will all be considered true,   all other values are considered false.  Example queries:      /run?filter=metadata.jenkins.job_name=jenkins_job     /run?filter=summary.failures>0 
     * Get a list of the test runs
     */
    getRunList(requestParameters: GetRunListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RunList>;

    /**
     * 
     * @summary Update a single run
     * @param {string} id ID of the test run
     * @param {Run} [run] A run object
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunApiInterface
     */
    updateRunRaw(requestParameters: UpdateRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Run>>;

    /**
     * Update a single run
     */
    updateRun(requestParameters: UpdateRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Run>;

}

/**
 * 
 */
export class RunApi extends runtime.BaseAPI implements RunApiInterface {

    /**
     * Create a run
     */
    async addRunRaw(requestParameters: AddRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Run>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/run`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RunToJSON(requestParameters['run']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RunFromJSON(jsonValue));
    }

    /**
     * Create a run
     */
    async addRun(requestParameters: AddRunRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Run> {
        const response = await this.addRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update multiple runs with common metadata
     */
    async bulkUpdateRaw(requestParameters: BulkUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RunList>> {
        const queryParameters: any = {};

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/runs/bulk-update`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRunToJSON(requestParameters['updateRun']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RunListFromJSON(jsonValue));
    }

    /**
     * Update multiple runs with common metadata
     */
    async bulkUpdate(requestParameters: BulkUpdateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RunList> {
        const response = await this.bulkUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a single run by ID (uuid required)
     */
    async getRunRaw(requestParameters: GetRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Run>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/run/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RunFromJSON(jsonValue));
    }

    /**
     * Get a single run by ID (uuid required)
     */
    async getRun(requestParameters: GetRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Run> {
        const response = await this.getRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The `filter` parameter takes a list of filters to apply in the form of:       {name}{operator}{value}   where:    - `name` is any valid column in the database   - `operator` is one of `=`, `!`, `＞`, `＜`, `)`, `(`, `~`, `*`   - `value` is what you want to filter by  Operators are simple correspondents to MongoDB\'s query selectors:    - `=` becomes `$eq`   - `!` becomes `$ne`   - `＞` becomes `$gt`   - `＜` becomes `$lt`   - `)` becomes `$gte`   - `(` becomes `$lte`   - `~` becomes `$regex`   - `*` becomes `$in`   - `@` becomes `$exists`  Notes:  - For the `$exists` operator, \"true\", \"t\", \"yes\", \"y\" and `1` will all be considered true,   all other values are considered false.  Example queries:      /run?filter=metadata.jenkins.job_name=jenkins_job     /run?filter=summary.failures>0 
     * Get a list of the test runs
     */
    async getRunListRaw(requestParameters: GetRunListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RunList>> {
        const queryParameters: any = {};

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['estimate'] != null) {
            queryParameters['estimate'] = requestParameters['estimate'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/run`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RunListFromJSON(jsonValue));
    }

    /**
     * The `filter` parameter takes a list of filters to apply in the form of:       {name}{operator}{value}   where:    - `name` is any valid column in the database   - `operator` is one of `=`, `!`, `＞`, `＜`, `)`, `(`, `~`, `*`   - `value` is what you want to filter by  Operators are simple correspondents to MongoDB\'s query selectors:    - `=` becomes `$eq`   - `!` becomes `$ne`   - `＞` becomes `$gt`   - `＜` becomes `$lt`   - `)` becomes `$gte`   - `(` becomes `$lte`   - `~` becomes `$regex`   - `*` becomes `$in`   - `@` becomes `$exists`  Notes:  - For the `$exists` operator, \"true\", \"t\", \"yes\", \"y\" and `1` will all be considered true,   all other values are considered false.  Example queries:      /run?filter=metadata.jenkins.job_name=jenkins_job     /run?filter=summary.failures>0 
     * Get a list of the test runs
     */
    async getRunList(requestParameters: GetRunListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RunList> {
        const response = await this.getRunListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a single run
     */
    async updateRunRaw(requestParameters: UpdateRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Run>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/run/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RunToJSON(requestParameters['run']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RunFromJSON(jsonValue));
    }

    /**
     * Update a single run
     */
    async updateRun(requestParameters: UpdateRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Run> {
        const response = await this.updateRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
