/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { CreateToken, Token, TokenList, User } from '../models/index';
import {
  CreateTokenFromJSON,
  CreateTokenToJSON,
  TokenFromJSON,
  TokenToJSON,
  TokenListFromJSON,
  TokenListToJSON,
  UserFromJSON,
  UserToJSON,
} from '../models/index';

export interface AddTokenRequest {
  createToken?: CreateToken;
}

export interface DeleteTokenRequest {
  id: string;
}

export interface GetTokenRequest {
  id: string;
}

export interface GetTokenListRequest {
  page?: number;
  pageSize?: number;
}

/**
 * UserApi - interface
 *
 * @export
 * @interface UserApiInterface
 */
export interface UserApiInterface {
  /**
   *
   * @summary Create a token for the current user
   * @param {CreateToken} [createToken] Create a token for a user
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserApiInterface
   */
  addTokenRaw(
    requestParameters: AddTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Token>>;

  /**
   * Create a token for the current user
   */
  addToken(
    requestParameters: AddTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Token>;

  /**
   *
   * @summary Delete the token
   * @param {string} id The id of a token
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserApiInterface
   */
  deleteTokenRaw(
    requestParameters: DeleteTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>>;

  /**
   * Delete the token
   */
  deleteToken(
    requestParameters: DeleteTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void>;

  /**
   *
   * @summary Return the user details for the current user
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserApiInterface
   */
  getCurrentUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>>;

  /**
   * Return the user details for the current user
   */
  getCurrentUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User>;

  /**
   *
   * @summary Retrieve a single token for the current user
   * @param {string} id The id of a token
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserApiInterface
   */
  getTokenRaw(
    requestParameters: GetTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Token>>;

  /**
   * Retrieve a single token for the current user
   */
  getToken(
    requestParameters: GetTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Token>;

  /**
   *
   * @summary Return the tokens for the user
   * @param {number} [page] Set the page of items to return, defaults to 1
   * @param {number} [pageSize] Set the number of items per page, defaults to 25
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserApiInterface
   */
  getTokenListRaw(
    requestParameters: GetTokenListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TokenList>>;

  /**
   * Return the tokens for the user
   */
  getTokenList(
    requestParameters: GetTokenListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TokenList>;

  /**
   *
   * @summary Return the user details for the current user
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserApiInterface
   */
  updateCurrentUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>>;

  /**
   * Return the user details for the current user
   */
  updateCurrentUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User>;
}

/**
 *
 */
export class UserApi extends runtime.BaseAPI implements UserApiInterface {
  /**
   * Create a token for the current user
   */
  async addTokenRaw(
    requestParameters: AddTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Token>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/user/token`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateTokenToJSON(requestParameters['createToken']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
  }

  /**
   * Create a token for the current user
   */
  async addToken(
    requestParameters: AddTokenRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Token> {
    const response = await this.addTokenRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Delete the token
   */
  async deleteTokenRaw(
    requestParameters: DeleteTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteToken().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/user/token/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete the token
   */
  async deleteToken(
    requestParameters: DeleteTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.deleteTokenRaw(requestParameters, initOverrides);
  }

  /**
   * Return the user details for the current user
   */
  async getCurrentUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/user`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
  }

  /**
   * Return the user details for the current user
   */
  async getCurrentUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
    const response = await this.getCurrentUserRaw(initOverrides);
    return await response.value();
  }

  /**
   * Retrieve a single token for the current user
   */
  async getTokenRaw(
    requestParameters: GetTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Token>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getToken().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/user/token/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TokenFromJSON(jsonValue));
  }

  /**
   * Retrieve a single token for the current user
   */
  async getToken(
    requestParameters: GetTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Token> {
    const response = await this.getTokenRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Return the tokens for the user
   */
  async getTokenListRaw(
    requestParameters: GetTokenListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TokenList>> {
    const queryParameters: any = {};

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['pageSize'] = requestParameters['pageSize'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/user/token`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TokenListFromJSON(jsonValue));
  }

  /**
   * Return the tokens for the user
   */
  async getTokenList(
    requestParameters: GetTokenListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TokenList> {
    const response = await this.getTokenListRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Return the user details for the current user
   */
  async updateCurrentUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/user`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
  }

  /**
   * Return the user details for the current user
   */
  async updateCurrentUser(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User> {
    const response = await this.updateCurrentUserRaw(initOverrides);
    return await response.value();
  }
}
