/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { WidgetConfig, WidgetConfigList } from '../models/index';
import {
  WidgetConfigFromJSON,
  WidgetConfigToJSON,
  WidgetConfigListFromJSON,
  WidgetConfigListToJSON,
} from '../models/index';

export interface AddWidgetConfigRequest {
  widgetConfig?: WidgetConfig;
}

export interface DeleteWidgetConfigRequest {
  id: string;
}

export interface GetWidgetConfigRequest {
  id: string;
}

export interface GetWidgetConfigListRequest {
  filter?: Array<string>;
  page?: number;
  pageSize?: number;
}

export interface UpdateWidgetConfigRequest {
  id: string;
  widgetConfig?: WidgetConfig;
}

/**
 * WidgetConfigApi - interface
 *
 * @export
 * @interface WidgetConfigApiInterface
 */
export interface WidgetConfigApiInterface {
  /**
   *
   * @summary Create a widget configuration
   * @param {WidgetConfig} [widgetConfig] Widget configuration
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WidgetConfigApiInterface
   */
  addWidgetConfigRaw(
    requestParameters: AddWidgetConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<WidgetConfig>>;

  /**
   * Create a widget configuration
   */
  addWidgetConfig(
    requestParameters: AddWidgetConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<WidgetConfig>;

  /**
   *
   * @summary Delete a widget configuration
   * @param {string} id ID of widget configuration to delete
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WidgetConfigApiInterface
   */
  deleteWidgetConfigRaw(
    requestParameters: DeleteWidgetConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>>;

  /**
   * Delete a widget configuration
   */
  deleteWidgetConfig(
    requestParameters: DeleteWidgetConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void>;

  /**
   *
   * @summary Get a single widget configuration
   * @param {string} id ID of widget config to return
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WidgetConfigApiInterface
   */
  getWidgetConfigRaw(
    requestParameters: GetWidgetConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<WidgetConfig>>;

  /**
   * Get a single widget configuration
   */
  getWidgetConfig(
    requestParameters: GetWidgetConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<WidgetConfig>;

  /**
   * A list of widget configurations
   * @summary Get the list of widget configurations
   * @param {Array<string>} [filter] Fields to filter by
   * @param {number} [page] Set the page of items to return, defaults to 1
   * @param {number} [pageSize] Set the number of items per page, defaults to 25
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WidgetConfigApiInterface
   */
  getWidgetConfigListRaw(
    requestParameters: GetWidgetConfigListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<WidgetConfigList>>;

  /**
   * A list of widget configurations
   * Get the list of widget configurations
   */
  getWidgetConfigList(
    requestParameters: GetWidgetConfigListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<WidgetConfigList>;

  /**
   *
   * @summary Updates a single widget configuration
   * @param {string} id ID of widget configuration to update
   * @param {WidgetConfig} [widgetConfig] Widget configuration
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WidgetConfigApiInterface
   */
  updateWidgetConfigRaw(
    requestParameters: UpdateWidgetConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<WidgetConfig>>;

  /**
   * Updates a single widget configuration
   */
  updateWidgetConfig(
    requestParameters: UpdateWidgetConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<WidgetConfig>;
}

/**
 *
 */
export class WidgetConfigApi extends runtime.BaseAPI implements WidgetConfigApiInterface {
  /**
   * Create a widget configuration
   */
  async addWidgetConfigRaw(
    requestParameters: AddWidgetConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<WidgetConfig>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/widget-config`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: WidgetConfigToJSON(requestParameters['widgetConfig']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => WidgetConfigFromJSON(jsonValue));
  }

  /**
   * Create a widget configuration
   */
  async addWidgetConfig(
    requestParameters: AddWidgetConfigRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<WidgetConfig> {
    const response = await this.addWidgetConfigRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Delete a widget configuration
   */
  async deleteWidgetConfigRaw(
    requestParameters: DeleteWidgetConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteWidgetConfig().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/widget-config/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete a widget configuration
   */
  async deleteWidgetConfig(
    requestParameters: DeleteWidgetConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.deleteWidgetConfigRaw(requestParameters, initOverrides);
  }

  /**
   * Get a single widget configuration
   */
  async getWidgetConfigRaw(
    requestParameters: GetWidgetConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<WidgetConfig>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getWidgetConfig().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/widget-config/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => WidgetConfigFromJSON(jsonValue));
  }

  /**
   * Get a single widget configuration
   */
  async getWidgetConfig(
    requestParameters: GetWidgetConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<WidgetConfig> {
    const response = await this.getWidgetConfigRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * A list of widget configurations
   * Get the list of widget configurations
   */
  async getWidgetConfigListRaw(
    requestParameters: GetWidgetConfigListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<WidgetConfigList>> {
    const queryParameters: any = {};

    if (requestParameters['filter'] != null) {
      queryParameters['filter'] = requestParameters['filter'];
    }

    if (requestParameters['page'] != null) {
      queryParameters['page'] = requestParameters['page'];
    }

    if (requestParameters['pageSize'] != null) {
      queryParameters['pageSize'] = requestParameters['pageSize'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/widget-config`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      WidgetConfigListFromJSON(jsonValue)
    );
  }

  /**
   * A list of widget configurations
   * Get the list of widget configurations
   */
  async getWidgetConfigList(
    requestParameters: GetWidgetConfigListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<WidgetConfigList> {
    const response = await this.getWidgetConfigListRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Updates a single widget configuration
   */
  async updateWidgetConfigRaw(
    requestParameters: UpdateWidgetConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<WidgetConfig>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling updateWidgetConfig().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/widget-config/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: WidgetConfigToJSON(requestParameters['widgetConfig']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => WidgetConfigFromJSON(jsonValue));
  }

  /**
   * Updates a single widget configuration
   */
  async updateWidgetConfig(
    requestParameters: UpdateWidgetConfigRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<WidgetConfig> {
    const response = await this.updateWidgetConfigRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
