/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { WidgetTypeList } from '../models/index';
import { WidgetTypeListFromJSON, WidgetTypeListToJSON } from '../models/index';

export interface GetWidgetRequest {
  id: string;
  params?: object;
}

export interface GetWidgetTypesRequest {
  type?: string;
}

/**
 * WidgetApi - interface
 *
 * @export
 * @interface WidgetApiInterface
 */
export interface WidgetApiInterface {
  /**
   *
   * @summary Generate data for a dashboard widget
   * @param {string} id The widget identifier
   * @param {object} [params] The parameters for the widget
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WidgetApiInterface
   */
  getWidgetRaw(
    requestParameters: GetWidgetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<object>>;

  /**
   * Generate data for a dashboard widget
   */
  getWidget(
    requestParameters: GetWidgetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<object>;

  /**
   * A list of widget types
   * @summary Get a list of widget types
   * @param {string} [type] Filter by type of widget
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WidgetApiInterface
   */
  getWidgetTypesRaw(
    requestParameters: GetWidgetTypesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<WidgetTypeList>>;

  /**
   * A list of widget types
   * Get a list of widget types
   */
  getWidgetTypes(
    requestParameters: GetWidgetTypesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<WidgetTypeList>;
}

/**
 *
 */
export class WidgetApi extends runtime.BaseAPI implements WidgetApiInterface {
  /**
   * Generate data for a dashboard widget
   */
  async getWidgetRaw(
    requestParameters: GetWidgetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<object>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getWidget().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['params'] != null) {
      queryParameters['params'] = requestParameters['params'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/widget/{id}`;
    urlPath = urlPath.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id'])));

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Generate data for a dashboard widget
   */
  async getWidget(
    requestParameters: GetWidgetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<object> {
    const response = await this.getWidgetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * A list of widget types
   * Get a list of widget types
   */
  async getWidgetTypesRaw(
    requestParameters: GetWidgetTypesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<WidgetTypeList>> {
    const queryParameters: any = {};

    if (requestParameters['type'] != null) {
      queryParameters['type'] = requestParameters['type'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwt', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/widget/types`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => WidgetTypeListFromJSON(jsonValue));
  }

  /**
   * A list of widget types
   * Get a list of widget types
   */
  async getWidgetTypes(
    requestParameters: GetWidgetTypesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<WidgetTypeList> {
    const response = await this.getWidgetTypesRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
