/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountReset
 */
export interface AccountReset {
    /**
     * The activation code generated by Ibutsu
     * @type {string}
     * @memberof AccountReset
     */
    activationCode: string;
    /**
     * The user's password
     * @type {string}
     * @memberof AccountReset
     */
    password: string;
}

/**
 * Check if a given object implements the AccountReset interface.
 */
export function instanceOfAccountReset(value: object): value is AccountReset {
    if (!('activationCode' in value) || value['activationCode'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AccountResetFromJSON(json: any): AccountReset {
    return AccountResetFromJSONTyped(json, false);
}

export function AccountResetFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountReset {
    if (json == null) {
        return json;
    }
    return {
        
        'activationCode': json['activation_code'],
        'password': json['password'],
    };
}

export function AccountResetToJSON(json: any): AccountReset {
    return AccountResetToJSONTyped(json, false);
}

export function AccountResetToJSONTyped(value?: AccountReset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activation_code': value['activationCode'],
        'password': value['password'],
    };
}

