/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AccountRegistration
 */
export interface AccountRegistration {
  /**
   * The user's e-mail address
   * @type {string}
   * @memberof AccountRegistration
   */
  email: string;
  /**
   * The user's password
   * @type {string}
   * @memberof AccountRegistration
   */
  password: string;
}

/**
 * Check if a given object implements the AccountRegistration interface.
 */
export function instanceOfAccountRegistration(value: object): value is AccountRegistration {
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('password' in value) || value['password'] === undefined) return false;
  return true;
}

export function AccountRegistrationFromJSON(json: any): AccountRegistration {
  return AccountRegistrationFromJSONTyped(json, false);
}

export function AccountRegistrationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AccountRegistration {
  if (json == null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
  };
}

export function AccountRegistrationToJSON(value?: AccountRegistration | null): any {
  return AccountRegistrationToJSONTyped(value, false);
}

export function AccountRegistrationToJSONTyped(
  value?: AccountRegistration | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value['email'],
    password: value['password'],
  };
}
