/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AccountRecovery
 */
export interface AccountRecovery {
    /**
     * The user's e-mail address
     * @type {string}
     * @memberof AccountRecovery
     */
    email: string;
}

/**
 * Check if a given object implements the AccountRecovery interface.
 */
export function instanceOfAccountRecovery(value: object): value is AccountRecovery {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function AccountRecoveryFromJSON(json: any): AccountRecovery {
    return AccountRecoveryFromJSONTyped(json, false);
}

export function AccountRecoveryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountRecovery {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function AccountRecoveryToJSON(value?: AccountRecovery | null): any {
    return AccountRecoveryToJSONTyped(value, false);
}

export function AccountRecoveryToJSONTyped(value?: AccountRecovery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

