/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Artifact
 */
export interface Artifact {
    /**
     * Unique ID of the artifact
     * @type {string}
     * @memberof Artifact
     */
    id?: string;
    /**
     * ID of test result to attach artifact to
     * @type {string}
     * @memberof Artifact
     */
    resultId?: string;
    /**
     * ID of test run to attach artifact to
     * @type {string}
     * @memberof Artifact
     */
    runId?: string;
    /**
     * name of the file
     * @type {string}
     * @memberof Artifact
     */
    filename?: string;
    /**
     * Additional data to pass to server
     * @type {object}
     * @memberof Artifact
     */
    additionalMetadata?: object;
    /**
     * The date this artifact was uploaded
     * @type {string}
     * @memberof Artifact
     */
    uploadDate?: string;
}

/**
 * Check if a given object implements the Artifact interface.
 */
export function instanceOfArtifact(value: object): value is Artifact {
    return true;
}

export function ArtifactFromJSON(json: any): Artifact {
    return ArtifactFromJSONTyped(json, false);
}

export function ArtifactFromJSONTyped(json: any, ignoreDiscriminator: boolean): Artifact {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'resultId': json['result_id'] == null ? undefined : json['result_id'],
        'runId': json['run_id'] == null ? undefined : json['run_id'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'additionalMetadata': json['additional_metadata'] == null ? undefined : json['additional_metadata'],
        'uploadDate': json['upload_date'] == null ? undefined : json['upload_date'],
    };
}

export function ArtifactToJSON(json: any): Artifact {
    return ArtifactToJSONTyped(json, false);
}

export function ArtifactToJSONTyped(value?: Artifact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'result_id': value['resultId'],
        'run_id': value['runId'],
        'filename': value['filename'],
        'additional_metadata': value['additionalMetadata'],
        'upload_date': value['uploadDate'],
    };
}

