/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Pagination } from './Pagination';
import {
  PaginationFromJSON,
  PaginationFromJSONTyped,
  PaginationToJSON,
  PaginationToJSONTyped,
} from './Pagination';
import type { Artifact } from './Artifact';
import {
  ArtifactFromJSON,
  ArtifactFromJSONTyped,
  ArtifactToJSON,
  ArtifactToJSONTyped,
} from './Artifact';

/**
 *
 * @export
 * @interface ArtifactList
 */
export interface ArtifactList {
  /**
   *
   * @type {Array<Artifact>}
   * @memberof ArtifactList
   */
  artifacts?: Array<Artifact>;
  /**
   *
   * @type {Pagination}
   * @memberof ArtifactList
   */
  pagination?: Pagination;
}

/**
 * Check if a given object implements the ArtifactList interface.
 */
export function instanceOfArtifactList(value: object): value is ArtifactList {
  return true;
}

export function ArtifactListFromJSON(json: any): ArtifactList {
  return ArtifactListFromJSONTyped(json, false);
}

export function ArtifactListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtifactList {
  if (json == null) {
    return json;
  }
  return {
    artifacts:
      json['artifacts'] == null
        ? undefined
        : (json['artifacts'] as Array<any>).map(ArtifactFromJSON),
    pagination: json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
  };
}

export function ArtifactListToJSON(value?: ArtifactList | null): any {
  return ArtifactListToJSONTyped(value, false);
}

export function ArtifactListToJSONTyped(
  value?: ArtifactList | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    artifacts:
      value['artifacts'] == null
        ? undefined
        : (value['artifacts'] as Array<any>).map(ArtifactToJSON),
    pagination: PaginationToJSON(value['pagination']),
  };
}
