/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateToken
 */
export interface CreateToken {
  /**
   * The name given to this token
   * @type {string}
   * @memberof CreateToken
   */
  name: string;
  /**
   * The date and time when this token expires
   * @type {string}
   * @memberof CreateToken
   */
  expires: string | null;
}

/**
 * Check if a given object implements the CreateToken interface.
 */
export function instanceOfCreateToken(value: object): value is CreateToken {
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('expires' in value) || value['expires'] === undefined) return false;
  return true;
}

export function CreateTokenFromJSON(json: any): CreateToken {
  return CreateTokenFromJSONTyped(json, false);
}

export function CreateTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateToken {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
    expires: json['expires'],
  };
}

export function CreateTokenToJSON(value?: CreateToken | null): any {
  return CreateTokenToJSONTyped(value, false);
}

export function CreateTokenToJSONTyped(
  value?: CreateToken | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    expires: value['expires'],
  };
}
