/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { Dashboard } from './Dashboard';
import {
    DashboardFromJSON,
    DashboardFromJSONTyped,
    DashboardToJSON,
    DashboardToJSONTyped,
} from './Dashboard';

/**
 * 
 * @export
 * @interface DashboardList
 */
export interface DashboardList {
    /**
     * 
     * @type {Array<Dashboard>}
     * @memberof DashboardList
     */
    dashboards?: Array<Dashboard>;
    /**
     * 
     * @type {Pagination}
     * @memberof DashboardList
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the DashboardList interface.
 */
export function instanceOfDashboardList(value: object): value is DashboardList {
    return true;
}

export function DashboardListFromJSON(json: any): DashboardList {
    return DashboardListFromJSONTyped(json, false);
}

export function DashboardListFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardList {
    if (json == null) {
        return json;
    }
    return {
        
        'dashboards': json['dashboards'] == null ? undefined : ((json['dashboards'] as Array<any>).map(DashboardFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function DashboardListToJSON(json: any): DashboardList {
    return DashboardListToJSONTyped(json, false);
}

export function DashboardListToJSONTyped(value?: DashboardList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dashboards': value['dashboards'] == null ? undefined : ((value['dashboards'] as Array<any>).map(DashboardToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

