/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface Dashboard
 */
export interface Dashboard {
    /**
     * Unique ID of the dashboard
     * @type {string}
     * @memberof Dashboard
     */
    id?: string;
    /**
     * The title of the dashboard
     * @type {string}
     * @memberof Dashboard
     */
    title?: string;
    /**
     * A basic description of the dashboard
     * @type {string}
     * @memberof Dashboard
     */
    description?: string;
    /**
     * An optional set of filters
     * @type {string}
     * @memberof Dashboard
     */
    filters?: string;
    /**
     * The ID of the project this dashboard is associated with
     * @type {string}
     * @memberof Dashboard
     */
    projectId?: string;
    /**
     * The ID of a user this dashboard might be associated with
     * @type {string}
     * @memberof Dashboard
     */
    userId?: string;
}

/**
 * Check if a given object implements the Dashboard interface.
 */
export function instanceOfDashboard(value: object): value is Dashboard {
    return true;
}

export function DashboardFromJSON(json: any): Dashboard {
    return DashboardFromJSONTyped(json, false);
}

export function DashboardFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dashboard {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'filters': json['filters'] == null ? undefined : json['filters'],
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function DashboardToJSON(value?: Dashboard | null): any {
    return DashboardToJSONTyped(value, false);
}

export function DashboardToJSONTyped(value?: Dashboard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'filters': value['filters'],
        'project_id': value['projectId'],
        'user_id': value['userId'],
    };
}

