/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Group } from './Group';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
    GroupToJSONTyped,
} from './Group';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';

/**
 * 
 * @export
 * @interface GroupList
 */
export interface GroupList {
    /**
     * 
     * @type {Array<Group>}
     * @memberof GroupList
     */
    groups?: Array<Group>;
    /**
     * 
     * @type {Pagination}
     * @memberof GroupList
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the GroupList interface.
 */
export function instanceOfGroupList(value: object): value is GroupList {
    return true;
}

export function GroupListFromJSON(json: any): GroupList {
    return GroupListFromJSONTyped(json, false);
}

export function GroupListFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupList {
    if (json == null) {
        return json;
    }
    return {
        
        'groups': json['groups'] == null ? undefined : ((json['groups'] as Array<any>).map(GroupFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function GroupListToJSON(json: any): GroupList {
    return GroupListToJSONTyped(json, false);
}

export function GroupListToJSONTyped(value?: GroupList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'groups': value['groups'] == null ? undefined : ((value['groups'] as Array<any>).map(GroupToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

