/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Health
 */
export interface Health {
    /**
     * The status of the database, one of "OK", "Error", "Pending"
     * @type {string}
     * @memberof Health
     */
    status?: string;
    /**
     * A message to explain the current status
     * @type {string}
     * @memberof Health
     */
    message?: string;
}

/**
 * Check if a given object implements the Health interface.
 */
export function instanceOfHealth(value: object): value is Health {
    return true;
}

export function HealthFromJSON(json: any): Health {
    return HealthFromJSONTyped(json, false);
}

export function HealthFromJSONTyped(json: any, ignoreDiscriminator: boolean): Health {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function HealthToJSON(json: any): Health {
    return HealthToJSONTyped(json, false);
}

export function HealthToJSONTyped(value?: Health | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
    };
}

