/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface HealthInfo
 */
export interface HealthInfo {
    /**
     * The URL of the frontend
     * @type {string}
     * @memberof HealthInfo
     */
    frontend?: string;
    /**
     * The URL of the backend
     * @type {string}
     * @memberof HealthInfo
     */
    backend?: string;
    /**
     * The URL to the UI for the API
     * @type {string}
     * @memberof HealthInfo
     */
    apiUi?: string;
}

/**
 * Check if a given object implements the HealthInfo interface.
 */
export function instanceOfHealthInfo(value: object): value is HealthInfo {
    return true;
}

export function HealthInfoFromJSON(json: any): HealthInfo {
    return HealthInfoFromJSONTyped(json, false);
}

export function HealthInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'frontend': json['frontend'] == null ? undefined : json['frontend'],
        'backend': json['backend'] == null ? undefined : json['backend'],
        'apiUi': json['api_ui'] == null ? undefined : json['api_ui'],
    };
}

export function HealthInfoToJSON(value?: HealthInfo | null): any {
    return HealthInfoToJSONTyped(value, false);
}

export function HealthInfoToJSONTyped(value?: HealthInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'frontend': value['frontend'],
        'backend': value['backend'],
        'api_ui': value['apiUi'],
    };
}

