/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Import
 */
export interface Import {
  /**
   * The database ID of the import
   * @type {string}
   * @memberof Import
   */
  id?: string;
  /**
   * The current status of the import, can be one of "pending", "running", "done"
   * @type {string}
   * @memberof Import
   */
  status?: string;
  /**
   * The name of the file that was uploaded
   * @type {string}
   * @memberof Import
   */
  filename?: string;
  /**
   * The format of the file uploaded
   * @type {string}
   * @memberof Import
   */
  format?: string;
  /**
   * The ID of the run from the import
   * @type {string}
   * @memberof Import
   */
  runId?: string;
}

/**
 * Check if a given object implements the Import interface.
 */
export function instanceOfImport(value: object): value is Import {
  return true;
}

export function ImportFromJSON(json: any): Import {
  return ImportFromJSONTyped(json, false);
}

export function ImportFromJSONTyped(json: any, ignoreDiscriminator: boolean): Import {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    status: json['status'] == null ? undefined : json['status'],
    filename: json['filename'] == null ? undefined : json['filename'],
    format: json['format'] == null ? undefined : json['format'],
    runId: json['run_id'] == null ? undefined : json['run_id'],
  };
}

export function ImportToJSON(value?: Import | null): any {
  return ImportToJSONTyped(value, false);
}

export function ImportToJSONTyped(
  value?: Import | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    status: value['status'],
    filename: value['filename'],
    format: value['format'],
    run_id: value['runId'],
  };
}
