/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LoginSupport
 */
export interface LoginSupport {
  /**
   * Flag to see if email/password login is available
   * @type {boolean}
   * @memberof LoginSupport
   */
  user?: boolean;
  /**
   * Flag to see if Keycloak login is available
   * @type {boolean}
   * @memberof LoginSupport
   */
  keycloak?: boolean;
  /**
   * Flag to see if Google login is available
   * @type {boolean}
   * @memberof LoginSupport
   */
  google?: boolean;
  /**
   * Flag to see if GitHub login is available
   * @type {boolean}
   * @memberof LoginSupport
   */
  github?: boolean;
  /**
   * Flag to see if Facebook login is available
   * @type {boolean}
   * @memberof LoginSupport
   */
  facebook?: boolean;
  /**
   * Flag to see if GitLab login is available
   * @type {boolean}
   * @memberof LoginSupport
   */
  gitlab?: boolean;
}

/**
 * Check if a given object implements the LoginSupport interface.
 */
export function instanceOfLoginSupport(value: object): value is LoginSupport {
  return true;
}

export function LoginSupportFromJSON(json: any): LoginSupport {
  return LoginSupportFromJSONTyped(json, false);
}

export function LoginSupportFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginSupport {
  if (json == null) {
    return json;
  }
  return {
    user: json['user'] == null ? undefined : json['user'],
    keycloak: json['keycloak'] == null ? undefined : json['keycloak'],
    google: json['google'] == null ? undefined : json['google'],
    github: json['github'] == null ? undefined : json['github'],
    facebook: json['facebook'] == null ? undefined : json['facebook'],
    gitlab: json['gitlab'] == null ? undefined : json['gitlab'],
  };
}

export function LoginSupportToJSON(value?: LoginSupport | null): any {
  return LoginSupportToJSONTyped(value, false);
}

export function LoginSupportToJSONTyped(
  value?: LoginSupport | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    user: value['user'],
    keycloak: value['keycloak'],
    google: value['google'],
    github: value['github'],
    facebook: value['facebook'],
    gitlab: value['gitlab'],
  };
}
