/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LoginError
 */
export interface LoginError {
  /**
   * An error code generated by the server
   * @type {string}
   * @memberof LoginError
   */
  code?: string;
  /**
   * The error message that corresponds with the error code
   * @type {string}
   * @memberof LoginError
   */
  message?: string;
}

/**
 * Check if a given object implements the LoginError interface.
 */
export function instanceOfLoginError(value: object): value is LoginError {
  return true;
}

export function LoginErrorFromJSON(json: any): LoginError {
  return LoginErrorFromJSONTyped(json, false);
}

export function LoginErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginError {
  if (json == null) {
    return json;
  }
  return {
    code: json['code'] == null ? undefined : json['code'],
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function LoginErrorToJSON(value?: LoginError | null): any {
  return LoginErrorToJSONTyped(value, false);
}

export function LoginErrorToJSONTyped(
  value?: LoginError | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value['code'],
    message: value['message'],
  };
}
