/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LoginToken
 */
export interface LoginToken {
  /**
   * The JWT token returned from a successful login
   * @type {string}
   * @memberof LoginToken
   */
  token?: string;
}

/**
 * Check if a given object implements the LoginToken interface.
 */
export function instanceOfLoginToken(value: object): value is LoginToken {
  return true;
}

export function LoginTokenFromJSON(json: any): LoginToken {
  return LoginTokenFromJSONTyped(json, false);
}

export function LoginTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginToken {
  if (json == null) {
    return json;
  }
  return {
    token: json['token'] == null ? undefined : json['token'],
  };
}

export function LoginTokenToJSON(value?: LoginToken | null): any {
  return LoginTokenToJSONTyped(value, false);
}

export function LoginTokenToJSONTyped(
  value?: LoginToken | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    token: value['token'],
  };
}
