/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LoginConfig
 */
export interface LoginConfig {
  /**
   * The client ID for the provider
   * @type {string}
   * @memberof LoginConfig
   */
  clientId?: string;
  /**
   * The redirect URI for the provider to call back
   * @type {string}
   * @memberof LoginConfig
   */
  redirectUri?: string;
  /**
   * The OAuth2 permission scope
   * @type {string}
   * @memberof LoginConfig
   */
  scope?: string;
}

/**
 * Check if a given object implements the LoginConfig interface.
 */
export function instanceOfLoginConfig(value: object): value is LoginConfig {
  return true;
}

export function LoginConfigFromJSON(json: any): LoginConfig {
  return LoginConfigFromJSONTyped(json, false);
}

export function LoginConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginConfig {
  if (json == null) {
    return json;
  }
  return {
    clientId: json['client_id'] == null ? undefined : json['client_id'],
    redirectUri: json['redirect_uri'] == null ? undefined : json['redirect_uri'],
    scope: json['scope'] == null ? undefined : json['scope'],
  };
}

export function LoginConfigToJSON(value?: LoginConfig | null): any {
  return LoginConfigToJSONTyped(value, false);
}

export function LoginConfigToJSONTyped(
  value?: LoginConfig | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    client_id: value['clientId'],
    redirect_uri: value['redirectUri'],
    scope: value['scope'],
  };
}
