/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Pagination
 */
export interface Pagination {
  /**
   * The current page number
   * @type {number}
   * @memberof Pagination
   */
  page?: number;
  /**
   * The number of items per page
   * @type {number}
   * @memberof Pagination
   */
  pageSize?: number;
  /**
   * The total number of pages
   * @type {number}
   * @memberof Pagination
   */
  totalPages?: number;
  /**
   * The total number of items for this query
   * @type {number}
   * @memberof Pagination
   */
  totalItems?: number;
}

/**
 * Check if a given object implements the Pagination interface.
 */
export function instanceOfPagination(value: object): value is Pagination {
  return true;
}

export function PaginationFromJSON(json: any): Pagination {
  return PaginationFromJSONTyped(json, false);
}

export function PaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pagination {
  if (json == null) {
    return json;
  }
  return {
    page: json['page'] == null ? undefined : json['page'],
    pageSize: json['pageSize'] == null ? undefined : json['pageSize'],
    totalPages: json['totalPages'] == null ? undefined : json['totalPages'],
    totalItems: json['totalItems'] == null ? undefined : json['totalItems'],
  };
}

export function PaginationToJSON(value?: Pagination | null): any {
  return PaginationToJSONTyped(value, false);
}

export function PaginationToJSONTyped(
  value?: Pagination | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    page: value['page'],
    pageSize: value['pageSize'],
    totalPages: value['totalPages'],
    totalItems: value['totalItems'],
  };
}
