/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Project
 */
export interface Project {
  /**
   * Unique ID of the project
   * @type {string}
   * @memberof Project
   */
  id?: string;
  /**
   * The machine name of the project
   * @type {string}
   * @memberof Project
   */
  name?: string;
  /**
   * The human-readable title of the project
   * @type {string}
   * @memberof Project
   */
  title?: string;
  /**
   * The ID of the owner of this project
   * @type {string}
   * @memberof Project
   */
  ownerId?: string | null;
  /**
   * The ID of the group of this project
   * @type {string}
   * @memberof Project
   */
  groupId?: string | null;
}

/**
 * Check if a given object implements the Project interface.
 */
export function instanceOfProject(value: object): value is Project {
  return true;
}

export function ProjectFromJSON(json: any): Project {
  return ProjectFromJSONTyped(json, false);
}

export function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    title: json['title'] == null ? undefined : json['title'],
    ownerId: json['owner_id'] == null ? undefined : json['owner_id'],
    groupId: json['group_id'] == null ? undefined : json['group_id'],
  };
}

export function ProjectToJSON(value?: Project | null): any {
  return ProjectToJSONTyped(value, false);
}

export function ProjectToJSONTyped(
  value?: Project | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    title: value['title'],
    owner_id: value['ownerId'],
    group_id: value['groupId'],
  };
}
