/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { Project } from './Project';
import {
    ProjectFromJSON,
    ProjectFromJSONTyped,
    ProjectToJSON,
    ProjectToJSONTyped,
} from './Project';

/**
 * 
 * @export
 * @interface ProjectList
 */
export interface ProjectList {
    /**
     * 
     * @type {Array<Project>}
     * @memberof ProjectList
     */
    projects?: Array<Project>;
    /**
     * 
     * @type {Pagination}
     * @memberof ProjectList
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the ProjectList interface.
 */
export function instanceOfProjectList(value: object): value is ProjectList {
    return true;
}

export function ProjectListFromJSON(json: any): ProjectList {
    return ProjectListFromJSONTyped(json, false);
}

export function ProjectListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectList {
    if (json == null) {
        return json;
    }
    return {
        
        'projects': json['projects'] == null ? undefined : ((json['projects'] as Array<any>).map(ProjectFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function ProjectListToJSON(json: any): ProjectList {
    return ProjectListToJSONTyped(json, false);
}

export function ProjectListToJSONTyped(value?: ProjectList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projects': value['projects'] == null ? undefined : ((value['projects'] as Array<any>).map(ProjectToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

