/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { Result } from './Result';
import {
    ResultFromJSON,
    ResultFromJSONTyped,
    ResultToJSON,
    ResultToJSONTyped,
} from './Result';

/**
 * 
 * @export
 * @interface ResultList
 */
export interface ResultList {
    /**
     * 
     * @type {Array<Result>}
     * @memberof ResultList
     */
    results?: Array<Result>;
    /**
     * 
     * @type {Pagination}
     * @memberof ResultList
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the ResultList interface.
 */
export function instanceOfResultList(value: object): value is ResultList {
    return true;
}

export function ResultListFromJSON(json: any): ResultList {
    return ResultListFromJSONTyped(json, false);
}

export function ResultListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultList {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ResultFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function ResultListToJSON(value?: ResultList | null): any {
    return ResultListToJSONTyped(value, false);
}

export function ResultListToJSONTyped(value?: ResultList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ResultToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

