/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Run
 */
export interface Run {
    /**
     * Unique ID of the test run
     * @type {string}
     * @memberof Run
     */
    id?: string;
    /**
     * The time this record was created
     * @type {string}
     * @memberof Run
     */
    created?: string;
    /**
     * Duration of tests in seconds
     * @type {number}
     * @memberof Run
     */
    duration?: number;
    /**
     * A source for this test run
     * @type {string}
     * @memberof Run
     */
    source?: string | null;
    /**
     * The time the test run started
     * @type {string}
     * @memberof Run
     */
    startTime?: string;
    /**
     * A component
     * @type {string}
     * @memberof Run
     */
    component?: string | null;
    /**
     * The environment which is being tested
     * @type {string}
     * @memberof Run
     */
    env?: string | null;
    /**
     * The project this run is associated with
     * @type {string}
     * @memberof Run
     */
    projectId?: string | null;
    /**
     * A summary of the test results
     * @type {object}
     * @memberof Run
     */
    summary?: object;
    /**
     * Extra metadata for this run
     * @type {object}
     * @memberof Run
     */
    metadata?: object | null;
}

/**
 * Check if a given object implements the Run interface.
 */
export function instanceOfRun(value: object): value is Run {
    return true;
}

export function RunFromJSON(json: any): Run {
    return RunFromJSONTyped(json, false);
}

export function RunFromJSONTyped(json: any, ignoreDiscriminator: boolean): Run {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'created': json['created'] == null ? undefined : json['created'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'source': json['source'] == null ? undefined : json['source'],
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
        'component': json['component'] == null ? undefined : json['component'],
        'env': json['env'] == null ? undefined : json['env'],
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function RunToJSON(json: any): Run {
    return RunToJSONTyped(json, false);
}

export function RunToJSONTyped(value?: Run | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created': value['created'],
        'duration': value['duration'],
        'source': value['source'],
        'start_time': value['startTime'],
        'component': value['component'],
        'env': value['env'],
        'project_id': value['projectId'],
        'summary': value['summary'],
        'metadata': value['metadata'],
    };
}

