/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { Run } from './Run';
import {
    RunFromJSON,
    RunFromJSONTyped,
    RunToJSON,
    RunToJSONTyped,
} from './Run';

/**
 * 
 * @export
 * @interface RunList
 */
export interface RunList {
    /**
     * 
     * @type {Array<Run>}
     * @memberof RunList
     */
    runs?: Array<Run>;
    /**
     * 
     * @type {Pagination}
     * @memberof RunList
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the RunList interface.
 */
export function instanceOfRunList(value: object): value is RunList {
    return true;
}

export function RunListFromJSON(json: any): RunList {
    return RunListFromJSONTyped(json, false);
}

export function RunListFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunList {
    if (json == null) {
        return json;
    }
    return {
        
        'runs': json['runs'] == null ? undefined : ((json['runs'] as Array<any>).map(RunFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function RunListToJSON(json: any): RunList {
    return RunListToJSONTyped(json, false);
}

export function RunListToJSONTyped(value?: RunList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'runs': value['runs'] == null ? undefined : ((value['runs'] as Array<any>).map(RunToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

