/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Token
 */
export interface Token {
  /**
   * The ID of the token
   * @type {string}
   * @memberof Token
   */
  id: string;
  /**
   * The ID of the user that owns this token
   * @type {string}
   * @memberof Token
   */
  userId: string;
  /**
   * The name given to this token
   * @type {string}
   * @memberof Token
   */
  name: string;
  /**
   * The date and time when this token expires
   * @type {string}
   * @memberof Token
   */
  expires?: string | null;
  /**
   * The token itself
   * @type {string}
   * @memberof Token
   */
  token: string;
}

/**
 * Check if a given object implements the Token interface.
 */
export function instanceOfToken(value: object): value is Token {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('userId' in value) || value['userId'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('token' in value) || value['token'] === undefined) return false;
  return true;
}

export function TokenFromJSON(json: any): Token {
  return TokenFromJSONTyped(json, false);
}

export function TokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Token {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    userId: json['user_id'],
    name: json['name'],
    expires: json['expires'] == null ? undefined : json['expires'],
    token: json['token'],
  };
}

export function TokenToJSON(value?: Token | null): any {
  return TokenToJSONTyped(value, false);
}

export function TokenToJSONTyped(value?: Token | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    user_id: value['userId'],
    name: value['name'],
    expires: value['expires'],
    token: value['token'],
  };
}
