/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Pagination } from './Pagination';
import {
  PaginationFromJSON,
  PaginationFromJSONTyped,
  PaginationToJSON,
  PaginationToJSONTyped,
} from './Pagination';
import type { Token } from './Token';
import { TokenFromJSON, TokenFromJSONTyped, TokenToJSON, TokenToJSONTyped } from './Token';

/**
 *
 * @export
 * @interface TokenList
 */
export interface TokenList {
  /**
   *
   * @type {Array<Token>}
   * @memberof TokenList
   */
  tokens?: Array<Token>;
  /**
   *
   * @type {Pagination}
   * @memberof TokenList
   */
  pagination?: Pagination;
}

/**
 * Check if a given object implements the TokenList interface.
 */
export function instanceOfTokenList(value: object): value is TokenList {
  return true;
}

export function TokenListFromJSON(json: any): TokenList {
  return TokenListFromJSONTyped(json, false);
}

export function TokenListFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenList {
  if (json == null) {
    return json;
  }
  return {
    tokens: json['tokens'] == null ? undefined : (json['tokens'] as Array<any>).map(TokenFromJSON),
    pagination: json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
  };
}

export function TokenListToJSON(value?: TokenList | null): any {
  return TokenListToJSONTyped(value, false);
}

export function TokenListToJSONTyped(
  value?: TokenList | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    tokens: value['tokens'] == null ? undefined : (value['tokens'] as Array<any>).map(TokenToJSON),
    pagination: PaginationToJSON(value['pagination']),
  };
}
