/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateRun
 */
export interface UpdateRun {
  /**
   * Extra data for this run
   * @type {object}
   * @memberof UpdateRun
   */
  metadata?: object;
}

/**
 * Check if a given object implements the UpdateRun interface.
 */
export function instanceOfUpdateRun(value: object): value is UpdateRun {
  return true;
}

export function UpdateRunFromJSON(json: any): UpdateRun {
  return UpdateRunFromJSONTyped(json, false);
}

export function UpdateRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRun {
  if (json == null) {
    return json;
  }
  return {
    metadata: json['metadata'] == null ? undefined : json['metadata'],
  };
}

export function UpdateRunToJSON(value?: UpdateRun | null): any {
  return UpdateRunToJSONTyped(value, false);
}

export function UpdateRunToJSONTyped(
  value?: UpdateRun | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    metadata: value['metadata'],
  };
}
