/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   * The ID of the user
   * @type {string}
   * @memberof User
   */
  id?: string;
  /**
   * The user's e-mail address
   * @type {string}
   * @memberof User
   */
  email: string;
  /**
   * The user's name
   * @type {string}
   * @memberof User
   */
  name?: string | null;
  /**
   * Flag to show if a user is a super-admin
   * @type {boolean}
   * @memberof User
   */
  isSuperadmin?: boolean;
  /**
   * Flag to show if the user is active
   * @type {boolean}
   * @memberof User
   */
  isActive?: boolean;
  /**
   * The ID of the group of this project
   * @type {string}
   * @memberof User
   */
  groupId?: string | null;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
  if (!('email' in value) || value['email'] === undefined) return false;
  return true;
}

export function UserFromJSON(json: any): User {
  return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    email: json['email'],
    name: json['name'] == null ? undefined : json['name'],
    isSuperadmin: json['is_superadmin'] == null ? undefined : json['is_superadmin'],
    isActive: json['is_active'] == null ? undefined : json['is_active'],
    groupId: json['group_id'] == null ? undefined : json['group_id'],
  };
}

export function UserToJSON(value?: User | null): any {
  return UserToJSONTyped(value, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    email: value['email'],
    name: value['name'],
    is_superadmin: value['isSuperadmin'],
    is_active: value['isActive'],
    group_id: value['groupId'],
  };
}
