/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WidgetConfig
 */
export interface WidgetConfig {
    /**
     * The internal ID of the WidgetConfig
     * @type {string}
     * @memberof WidgetConfig
     */
    id?: string;
    /**
     * The type of widget, one of either "widget" or "view"
     * @type {string}
     * @memberof WidgetConfig
     */
    type?: string;
    /**
     * The widget to render, from the list at /widget/types
     * @type {string}
     * @memberof WidgetConfig
     */
    widget?: string;
    /**
     * The project ID for which the widget is designed
     * @type {string}
     * @memberof WidgetConfig
     */
    projectId?: string;
    /**
     * The weighting for the widget, lower weight means it will display first
     * @type {number}
     * @memberof WidgetConfig
     */
    weight?: number;
    /**
     * A dictionary of parameters to send to the widget
     * @type {object}
     * @memberof WidgetConfig
     */
    params?: object;
    /**
     * The title shown on the widget or page
     * @type {string}
     * @memberof WidgetConfig
     */
    title?: string;
}

/**
 * Check if a given object implements the WidgetConfig interface.
 */
export function instanceOfWidgetConfig(value: object): value is WidgetConfig {
    return true;
}

export function WidgetConfigFromJSON(json: any): WidgetConfig {
    return WidgetConfigFromJSONTyped(json, false);
}

export function WidgetConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'widget': json['widget'] == null ? undefined : json['widget'],
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'params': json['params'] == null ? undefined : json['params'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function WidgetConfigToJSON(json: any): WidgetConfig {
    return WidgetConfigToJSONTyped(json, false);
}

export function WidgetConfigToJSONTyped(value?: WidgetConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'widget': value['widget'],
        'project_id': value['projectId'],
        'weight': value['weight'],
        'params': value['params'],
        'title': value['title'],
    };
}

