/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface WidgetParam
 */
export interface WidgetParam {
    /**
     * The name of the parameter to supply to the widget
     * @type {string}
     * @memberof WidgetParam
     */
    name?: string;
    /**
     * A friendly description of the parameter
     * @type {string}
     * @memberof WidgetParam
     */
    description?: string;
    /**
     * The type of parameter (string, integer, etc)
     * @type {string}
     * @memberof WidgetParam
     */
    type?: string;
}

/**
 * Check if a given object implements the WidgetParam interface.
 */
export function instanceOfWidgetParam(value: object): value is WidgetParam {
    return true;
}

export function WidgetParamFromJSON(json: any): WidgetParam {
    return WidgetParamFromJSONTyped(json, false);
}

export function WidgetParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetParam {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function WidgetParamToJSON(value?: WidgetParam | null): any {
    return WidgetParamToJSONTyped(value, false);
}

export function WidgetParamToJSONTyped(value?: WidgetParam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
    };
}

