/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { WidgetParam } from './WidgetParam';
import {
    WidgetParamFromJSON,
    WidgetParamFromJSONTyped,
    WidgetParamToJSON,
    WidgetParamToJSONTyped,
} from './WidgetParam';

/**
 * 
 * @export
 * @interface WidgetType
 */
export interface WidgetType {
    /**
     * A unique identifier for this widget type
     * @type {string}
     * @memberof WidgetType
     */
    id?: string;
    /**
     * The title of the widget, for users to see
     * @type {string}
     * @memberof WidgetType
     */
    title?: string;
    /**
     * A helpful description of this widget type
     * @type {string}
     * @memberof WidgetType
     */
    description?: string;
    /**
     * A dictionary or map of parameters to values
     * @type {Array<WidgetParam>}
     * @memberof WidgetType
     */
    params?: Array<WidgetParam>;
    /**
     * The type of widget (widget, view)
     * @type {string}
     * @memberof WidgetType
     */
    type?: string;
}

/**
 * Check if a given object implements the WidgetType interface.
 */
export function instanceOfWidgetType(value: object): value is WidgetType {
    return true;
}

export function WidgetTypeFromJSON(json: any): WidgetType {
    return WidgetTypeFromJSONTyped(json, false);
}

export function WidgetTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'params': json['params'] == null ? undefined : ((json['params'] as Array<any>).map(WidgetParamFromJSON)),
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function WidgetTypeToJSON(value?: WidgetType | null): any {
    return WidgetTypeToJSONTyped(value, false);
}

export function WidgetTypeToJSONTyped(value?: WidgetType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'params': value['params'] == null ? undefined : ((value['params'] as Array<any>).map(WidgetParamToJSON)),
        'type': value['type'],
    };
}

