/* tslint:disable */
/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Pagination } from './Pagination';
import {
  PaginationFromJSON,
  PaginationFromJSONTyped,
  PaginationToJSON,
  PaginationToJSONTyped,
} from './Pagination';
import type { WidgetType } from './WidgetType';
import {
  WidgetTypeFromJSON,
  WidgetTypeFromJSONTyped,
  WidgetTypeToJSON,
  WidgetTypeToJSONTyped,
} from './WidgetType';

/**
 *
 * @export
 * @interface WidgetTypeList
 */
export interface WidgetTypeList {
  /**
   *
   * @type {Array<WidgetType>}
   * @memberof WidgetTypeList
   */
  types?: Array<WidgetType>;
  /**
   *
   * @type {Pagination}
   * @memberof WidgetTypeList
   */
  pagination?: Pagination;
}

/**
 * Check if a given object implements the WidgetTypeList interface.
 */
export function instanceOfWidgetTypeList(value: object): value is WidgetTypeList {
  return true;
}

export function WidgetTypeListFromJSON(json: any): WidgetTypeList {
  return WidgetTypeListFromJSONTyped(json, false);
}

export function WidgetTypeListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): WidgetTypeList {
  if (json == null) {
    return json;
  }
  return {
    types:
      json['types'] == null ? undefined : (json['types'] as Array<any>).map(WidgetTypeFromJSON),
    pagination: json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
  };
}

export function WidgetTypeListToJSON(value?: WidgetTypeList | null): any {
  return WidgetTypeListToJSONTyped(value, false);
}

export function WidgetTypeListToJSONTyped(
  value?: WidgetTypeList | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    types:
      value['types'] == null ? undefined : (value['types'] as Array<any>).map(WidgetTypeToJSON),
    pagination: PaginationToJSON(value['pagination']),
  };
}
