/* eslint-disable */
/**
 * Ibutsu API
 * A system to store and query test results
 *
 * The version of the OpenAPI document: 2.8.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Pagination } from './Pagination';
import {
  PaginationFromJSON,
  PaginationFromJSONTyped,
  PaginationToJSON,
  PaginationToJSONTyped,
} from './Pagination';
import type { WidgetConfig } from './WidgetConfig';
import {
  WidgetConfigFromJSON,
  WidgetConfigFromJSONTyped,
  WidgetConfigToJSON,
  WidgetConfigToJSONTyped,
} from './WidgetConfig';

/**
 *
 * @export
 * @interface WidgetConfigList
 */
export interface WidgetConfigList {
  /**
   *
   * @type {Array<WidgetConfig>}
   * @memberof WidgetConfigList
   */
  widgets?: Array<WidgetConfig>;
  /**
   *
   * @type {Pagination}
   * @memberof WidgetConfigList
   */
  pagination?: Pagination;
}

/**
 * Check if a given object implements the WidgetConfigList interface.
 */
export function instanceOfWidgetConfigList(value: object): value is WidgetConfigList {
  return true;
}

export function WidgetConfigListFromJSON(json: any): WidgetConfigList {
  return WidgetConfigListFromJSONTyped(json, false);
}

export function WidgetConfigListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): WidgetConfigList {
  if (json == null) {
    return json;
  }
  return {
    widgets:
      json['widgets'] == null
        ? undefined
        : (json['widgets'] as Array<any>).map(WidgetConfigFromJSON),
    pagination: json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
  };
}

export function WidgetConfigListToJSON(value?: WidgetConfigList | null): any {
  return WidgetConfigListToJSONTyped(value, false);
}

export function WidgetConfigListToJSONTyped(
  value?: WidgetConfigList | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    widgets:
      value['widgets'] == null
        ? undefined
        : (value['widgets'] as Array<any>).map(WidgetConfigToJSON),
    pagination: PaginationToJSON(value['pagination']),
  };
}
